### ISSUE TITLE
聚合查询如果第一个分库查询返回null，merge结果不对

### ISSUE THREAD

**Issue by koaal** [dangdangdotcom/sharding-jdbc#100]
应用场景：
两个分库，db0和db1，只分库不分表
查询语句：select min(id) from table where datatime >= xxxx

当第一个分库查询返回结果为null，第二个分库查询返回结果不为null时（比如101），merge后返回的结果为null，正确返回结果应该为101

问题分析：
该sql会被改写为两条sql执行并返回两个ResultSet，其中第一个resultset的wasNull为true，第二个为false。AbstractResultSetAdapter里重载的wasNull函数直接返回getCurrentResultSet().wasNull()，而currentResultSet被指定为第一个ResultSet，所以wasNull返回true

**Comment by koaal** [comment]
版本1.1.0

**Comment by terrymanu** [comment]
在1.3.0版本已对结果归并模块做出重大调整，请使用1.3.0尝试，如还有问题，请反馈，多谢

**Comment by terrymanu** [comment]
长时间无反馈。如有问题，请跟进，如无问题，我们将于三天后以不能重现为由关闭此bug

**Comment by terrymanu** [comment]
不能重现
