### ISSUE TITLE
master-slave的聚合查询

### ISSUE THREAD

**Issue by IBYoung** [dangdangdotcom/sharding-jdbc#104]
在使用SpringNamespaceWithMasterSlaveMain测试类访问的时候，sql不管是有条件的还是无条件的
`SELECT i.* FROM t_order o JOIN t_order_item i ON o.order_id=i.order_id `没有数据展示

**Comment by terrymanu** [comment]
读写分离并不提供主库和从库的数据同步。
example的例子是向主库插入，然后从从库读取时确实没数据，因为主从同步是数据库端的配置
