### ISSUE TITLE
PreparedStatement预编译一次，多次set值多次executeUpdate数据相同

### ISSUE THREAD

**Issue by xuchanggen** [dangdangdotcom/sharding-jdbc#106]
DataSource dataSource = getShardingDataSource();
		String sql = "insert ignore into t_user(login_code,user_name,age,telephone,address) values(?,?,?,?,?)";
		try (
			Connection conn = dataSource.getConnection();
            PreparedStatement **ps = conn.prepareStatement(sql);**){
			List<User> userList = getUserList(20);
			for(User user:userList){
				ps.setString(1, user.getLoginCode());
				ps.setString(2, user.getUserName());
				ps.setInt(3, user.getAge());
				ps.setString(4, user.getTelephone());
				ps.setString(5, user.getAddress());
				**ps.executeUpdate();**
			}
			ps.close();
			conn.close();
		}

**Comment by xuchanggen** [comment]
![image](https://cloud.githubusercontent.com/assets/11846322/16170810/da453ad8-3591-11e6-8a77-684b36f9547c.png)

**Comment by xuchanggen** [comment]
![image](https://cloud.githubusercontent.com/assets/11846322/16170812/ec552ae4-3591-11e6-82f6-e0ec078b03c4.png)

**Comment by xuchanggen** [comment]
TableRule.builder("t_user").actualTables(Arrays.asList("t_user_0", "t_user_1", "t_user_2"));实际有三张表。这种情况下都往t_user_1表中写了。getShardingDataSource()换成原生的，数据不会相同。
ps = conn.prepareStatement(sql);放入for循环中正常，会正常往三张表里面写！

**Comment by hanahmily** [comment]
合并到 #36
