### ISSUE TITLE
insert之后执行:SELECT @@IDENTITY报错

### ISSUE THREAD

**Issue by xuchanggen** [dangdangdotcom/sharding-jdbc#107]
1.3.0版本和1.3.1SNAPSHUT版本都尝试了。insert之后执行SELECT @@IDENTITY会报错： com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: Sharding-JDBC: **cannot route any result, please check your sharding rule.**

**Comment by xuchanggen** [comment]
![image](https://cloud.githubusercontent.com/assets/11846322/16182176/9f67ce2c-36d5-11e6-9062-08d2cfdea8a8.png)
期望能够支持这个SELECT @@IDENTITY

**Comment by hanahmily** [comment]
@xuchanggen 目前不支持@@IDENTITY 获取最后一次执行的值。原因是SJDBC不支持自增长字段，而@@IDENTITY其实是为了自增长字段服务的。
而您截图中的例子中，开发人员是自己实现的数据插入，这应该不需要@@IDENTITY的帮助也可以获取到这个值。
SJDBC经过主要维护人员内部的讨论，觉得应该通过实现统一生成分布式序列的方式来支持主键生成或序列生成这样的任务，而不是通过实现自增序列来达到该目的。
故目前没有实现@@IDENTITY必要，也没有相关计划要支持。

**Comment by xuchanggen** [comment]
谢谢！ @hanahmily
