### ISSUE TITLE
TableRule  actualTables 实际表的配置 支持现有方式 能不能再支持自定义规则

### ISSUE THREAD

**Issue by deeplyloving** [dangdangdotcom/sharding-jdbc#108]
能不能支持一下 建表语句?
如果 支持 建表语句  TableRule  actualTables 实际表的配置 支持现有方式 能不能再支持自定义规则?
如果能  那么就可以根据  TableRule  actualTables 实际表的配置 来取对应的表 即现在的 表策略.如果发现该表不存在.则从 实际表规则模板中 获取创建表语句 自动创建 表结构

**Comment by terrymanu** [comment]
能不能再说的详细些，我没完全理解。
如果是支持建表语句，是非常大的新功能开发，可以单独提issue，最好不要混在一起讨论。
actualTables就是真实表名，请问自定义规则是什么意思？

**Comment by terrymanu** [comment]
duplicate with #62
