### ISSUE TITLE
跨分片关联查询支持

### ISSUE THREAD

**Issue by deeplyloving** [dangdangdotcom/sharding-jdbc#109]
sharding-jdbc版本 1.3.0

实体表与虚拟表 left join  right join 查询 返回值不正确

库 db0  db1   默认数据源库 db0
db0表  test0   test1   test3
db1表  test0   test1 

test0 test1 映射成  test 虚拟表   表字段为 id,code    分库策略为 id 取模  分表策略为  code取模
test3 表字段为 id code test_id(对应test虚拟表id)

按规则插入数据,db0 db1中的test0   test1 均有值(执行 简单sql均无问题 如 in 能取到各个库表中数据合集),,,手动添加 test3数据 执行下面的left join语句
select \* from test3 as t1 left join test as t2 on t1.test_id = t2.id

问题有2
问题1:返回的结果行数不正确. 如 实体表 test3中有5条数据 且 test_id 均有正确设置(test_id分布在两个库中)  返回的结果有10条数据. 
问题2: 只能关联到 db0 中的 test 数据    db1中的数据无法关联

问题可能出现在

CartesianTablesRouter  getIntersectionDataSources() 取交集方法
db0 与  db0 db1     取并集结果为  db0   因此只查 db0的数据.
若取合集将出现 test3在 db1中不存在

**Comment by hanahmily** [comment]
问题1：请提供每张表的数据，仅凭描述我并不能复现这个问题。
问题2：这是sjdbc的特性，sjdbc不支持跨数据库的join，故只能join同一个数据库内部的表

**Comment by deeplyloving** [comment]
@hanahmily     重现问题很简单。只要做 分库 分表。 用 实体表 关联查询 虚拟表。
 
         sjdbc不支持跨数据库的join?  虚拟表之间的 join 是否跨库？

**Comment by hanahmily** [comment]
@deeplyloving 这两个问题归结起来就是sjdbc并不支持跨库的表链接。也就是test3无法与db1中的表做链接，这个可以作为新功能后续实现。

**Comment by hanahmily** [comment]
#131 合并进来
