### ISSUE TITLE
对limit支持的bug

### ISSUE THREAD

**Issue by wangkang007** [dangdangdotcom/sharding-jdbc#112]
limit 0,10
user_id: 1000
user_id: 1002
user_id: 1004
user_id: 1006
user_id: 1008
user_id: 1100
user_id: 1102
user_id: 1104
user_id: 1106
user_id: 1108

limit 10,20
user_id: 1100
user_id: 1102
user_id: 1104
user_id: 1106
user_id: 1108
user_id: 1101
user_id: 1103
user_id: 1105
user_id: 1107
user_id: 1109

我用master的代码，发现使用limit的时候会造成数据的重复，不知道这个有没有什么解决办法

**Comment by hanahmily** [comment]
@wangkang007 请发送一下sql的写法，还有你的分片的策略，谢谢

**Comment by terrymanu** [comment]
长时间无反馈，issue关闭
