### ISSUE TITLE
Select语句包含or条件，分页不正确。

### ISSUE THREAD

**Issue by bcllemon** [dangdangdotcom/sharding-jdbc#126]
分表规则：根据日期，按月分表。
sql(分页正常)：
```sql
SELECT FundActivityID 
             FROM fund_activities 
             WHERE (CreateAt BETWEEN :StartTime AND :EndTime) 
              AND IsValid=1 
               ORDER BY PayTime DESC LIMIT :Skip, :Take;
```
sql(分页错误):
```sql
SELECT FundActivityID 
             FROM fund_activities 
             WHERE (CreateAt BETWEEN :StartTime AND :EndTime) 
              AND IsValid=1 
            AND (FromUserID=xx OR ToUserID=xx)
             ORDER BY PayTime DESC LIMIT :Skip, :Take;
```
[FundActivityTableShardingAlgorithm.java.txt](https://github.com/dangdangdotcom/sharding-jdbc/files/395163/FundActivityTableShardingAlgorithm.java.txt)

[ShardingDataSourceFactoryBean.java.txt](https://github.com/dangdangdotcom/sharding-jdbc/files/395159/ShardingDataSourceFactoryBean.java.txt)

[trace_log.txt](https://github.com/dangdangdotcom/sharding-jdbc/files/395155/trace_log.txt)

**Comment by hanahmily** [comment]
您使用的版本是1.3.1吧？这个bug在1.3.2-SNAPSHOT中已经修复了。

**Comment by bcllemon** [comment]
这个版本还没有发布吧？
