### ISSUE TITLE
多个数据源含有未分片数据源场景下，当未配置虚拟表dataSourceNames时，分片表会路由到未分片数据源

### ISSUE THREAD

**Issue by tietang** [dangdangdotcom/sharding-jdbc#127]
> 

> `

dataSource:
  ds_0: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.4.171/ds_0
    username: root
    password: 123456
  ds_1: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.4.171/ds_1
    username: root
    password: 123456
  cloud: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.4.171/cloud
    username: root
    password: 123456

defaultDataSourceName: cloud

tables:
  config:
    actualTables: t_config

  t_order:
    actualTables: t_order_${0..1}
    ##dataSourceNames: ds_0,ds_1
    tableStrategy: &table001
      shardingColumns: order_id
      algorithmExpression: t_order_${order_id.longValue() % 2}

  #绑定表中其余的表的策略与t_order的策略相同
  t_order_item:
    actualTables: t_order_item_${0..1}
    ##dataSourceNames: ds_0,ds_1
    tableStrategy: *table001

bindingTables:
  - tableNames: t_order,t_order_item
#  - tableNames: ...

defaultDatabaseStrategy:
  shardingColumns: user_id
  algorithmExpression: ds_${user_id.longValue() % 2}

defaultTableStrategy:
  shardingColumns:  order_id
  algorithmClassName: example.algorithm.SingleKeyModuloTableShardingAlgorithm

props:
  metrics.enable: true

`

如上配置，有3个数据源，其中ds_0,ds_1为分片数据源，cloud为不分片默认数据源。

当不配置虚拟表dataSourceNames时，会将 t_order,t_order_item路由到cloud的数据源，预期应该是ds_0或者ds_1数据源。如果配置了虚拟表dataSourceNames则正常。

**Comment by hanahmily** [comment]
默认数据源是个兜底概念，也就是这个表实在不知道去哪里路由了，就去默认数据源里面找。而你如果不配置dataSourceNames，那么说明你的这个逻辑表散步在所有的数据源内，那么自然也包含默认数据源内。

**Comment by tietang** [comment]
但是，我的疑问是：

defaultDatabaseStrategy:
shardingColumns: user_id
algorithmExpression: ds_${user_id.longValue() % 2}

这个配置中不是已经可以计算出通过数据源名称了么，那么通过名称就可以在所有数据源里面匹配啊？
