### ISSUE TITLE
绑定表分片值可以进行传递给整个绑定表群组内

### ISSUE THREAD

**Issue by lalahei** [dangdangdotcom/sharding-jdbc#129]
order和sub_order是绑定表，都以order_id进行分表。
写法一（正确的写法）：SELECT \* FROM order,sub_order WHERE order.order_id = sub_order.order_id and order.order_id = ?
写法二（错误的写法）：SELECT \* FROM sub_order,order WHERE order.order_id = sub_order.order_id and order.order_id = ?
写法二会导致不进行分表计算，很容易造成陷阱，可能是因为选主的算法，FROM后面的第一个表认为是主表，所用的绑定表的分库分别规则都以主表为准。所以写法二认为主表是sub_order，但是where条件中却是order.order_id，所以就不进行分表计算。

**Comment by pan289091315** [comment]
现在还有这个问题吗？怎么我这里好像复现不了？

**Comment by hanahmily** [comment]
还是这样的 文档里面也有描述。后续可能改造成 将order_id=1这个条件传递给sub_order，这样选哪个是主表也就没关系了

**Comment by terrymanu** [comment]
绑定表分片值以及分片策略必须完全一致，因此无需传递，直接推导即可。
