### ISSUE TITLE
写文档说明对于分页问题的优化

### ISSUE THREAD

**Issue by lalahei** [dangdangdotcom/sharding-jdbc#130]
分页的查询请求，如果落在了多个库多个表，得到了多个结果集，如果获取最后一页，sjdbc的处理方式是时查询全量的结果集，然后移动游标到最后一页，这样很容易照成内存溢出或大量网络请求的消耗（取决于你设置的fetchsize的大小）。

**Comment by terrymanu** [comment]
这有什么更好的解决方案么

**Comment by jiang2015** [comment]
这个问题有好的解决方案或者思路了吗

**Comment by hanahmily** [comment]
这个方案是有的

1. 如果使用limit， 前提是要假设各个分片数据是均匀的。这样就可以合理推断每个分片可以跳过固定的数据，这样可以大大减少提取的数据量。

1. 不用limit，分页的时候使用特定字段（比如使用创建时间）排序，然后分页点使用该字段。这样每一页提取的数据就差不多了。

**Comment by hanahmily** [comment]
可以将这个问题写成文档分享出来

**Comment by liyichengcheng** [comment]
不用limit，分页的时候使用特定字段（比如使用创建时间）排序，然后分页点使用该字段。这样每一页提取的数据就差不多了。用创建时间排序也不能保证各分表的数据均匀啊，可能某一段很长时间插入的数据都在一个分表。

**Comment by liyichengcheng** [comment]
如果是查询倒数页的话，其实不用 “查询全量的结果集，然后移动游标到最后一页”，把 order by asc 改成 desc, 或者 把 desc 改 asc 取前几页就可以了
