### ISSUE TITLE
表关联查询，需要跨库关联

### ISSUE THREAD

**Issue by lalahei** [dangdangdotcom/sharding-jdbc#131]
进行了分库分表，两个表关联查询，查询条件中没有分库字段，目前这种笛卡儿积的处理方式有问题，因为目前只在一个库中做笛卡儿积，没有跨库做，这样的查询结果应该是不准确的，如果不支持跨库的关联查询，是否考虑碰到类似的sql时，直接抛异常。如果不抛异常，很可能是个陷阱。

**Comment by hanahmily** [comment]
抛异常是一个主意。不过我倾向于将这种行为做成一个配置，给一个全局配置应该就足够了

**Comment by hanahmily** [comment]
合并到 #109

**Comment by 2018CC** [comment]
先sharding 跨库联合查询可以实现吗
