### ISSUE TITLE
spring boot xml配置中xmlns:rdb配置报错

### ISSUE THREAD

**Issue by guanz231** [dangdangdotcom/sharding-jdbc#140]
参考sample进行配置

报错信息如下

org.xml.sax.SAXParseException: schema_reference.4: 无法读取方案文档 'http://www.dangdang.com/schema/ddframe/rdb/rdb.xsd', 原因为 1) 无法找到文档; 2) 无法读取文档; 3) 文档的根元素不是 <xsd:schema>

**Comment by zengyintian** [comment]
添加依赖 sharding-jdbc-config-spring

**Comment by duomu** [comment]
添加了还是报错呀
