### ISSUE TITLE
ShardingConnection.getConnectionInternal 并发同步问题(V1.3.2)

### ISSUE THREAD

**Issue by Beyondeclipse** [dangdangdotcom/sharding-jdbc#145]
在1.3.2版本中，如果多线程跑ShardingPreparedStatement.addBatch时，将调用ShardingConnection.getConnectionInternal取得Connection，则此时由于没有同步机制，2个相同dataSourceName请求可能重复取Connection，而其中一个不会被put到connectionMap。

**Comment by hanahmily** [comment]
sjdbc的api中，只有ShardingDataSource是线程安全的，其他api均不是线程安全的。故请使用者自己实现保护机制。
