### ISSUE TITLE
与最新SQLserver jdbc驱动兼容问题

### ISSUE THREAD

**Issue by boying52** [dangdangdotcom/sharding-jdbc#150]
public String getDatabaseProductName() throws SQLServerException {
        this.checkClosed();
        return "Microsoft SQL Server";
    }

新驱动的PN是这个，导致不能转换shardingDataSource

**Comment by hanahmily** [comment]
该方法在主流数据库驱动中一般都是显示声明了一个字符串，数据库与该字符串对应关系如下：
 - H2 : "H2"
 - MySQL : "MySQL"
 - Oracle ："Oracle"
 - SQLServer ："Microsoft SQL Server"

可以观察到只有微软的SQLServer较为特殊。

对于IBM的DB2情况较为复杂，从驱动的源代码看该值不是显示声明而是从数据库动态获取的。从[jdbc驱动文档](https://www.ibm.com/support/knowledgecenter/SSEPEK_10.0.0/java/src/tpc/imjcc_c0053013.html)中看取值可能由于安装的平台不同而不同。

故sjdbc针对DB2将使用其“DB2 for Linux, UNIX, and Windows on Linux on x86”平台上的名字"DB2"
