### ISSUE TITLE
两张分片表，left jion 结果异常

### ISSUE THREAD

**Issue by Jakye** [dangdangdotcom/sharding-jdbc#151]
对两表进行分片t_order 按order_id与create_time分片，t_user_order 按user_id分片
`SELECT t_user_order.order_id, t_user_order.user_id, t_user_order.remark, t_order.status, t_user_order.create_time FROM t_order LEFT JOIN t_user_order ON t_order.order_id = t_user_order.order_id WHERE t_order.order_id > 9 AND t_order_0_2016_q1.order_id <99`
结果异常
![qq 20161011175734](https://cloud.githubusercontent.com/assets/7413897/19266939/835154ee-8fde-11e6-9a7f-2130825c6e28.jpg)
前面的值正确得到后面的值错了，

**Comment by hanahmily** [comment]
请如#153 一样提交详细的日志 否则没有办法问题分析

**Comment by Jakye** [comment]
改为inner join结果正常
