### ISSUE TITLE
sqlParsedResult 缓存多数情况下不会命中

### ISSUE THREAD

**Issue by yuanwhy** [dangdangdotcom/sharding-jdbc#156]
sql parse 过程有的时候挺耗时，ShardingPreparedStatement每次新建preparedSQLRouter，

![image](https://cloud.githubusercontent.com/assets/4101682/19407973/3dc3e51e-92e4-11e6-887c-95391587cf64.png)

![image](https://cloud.githubusercontent.com/assets/4101682/19407977/4e65a88a-92e4-11e6-878e-3092ab8d9060.png)

preparedSQLRouter中有sqlParsedResult，`只有在复用ShardingPreparedStatement的时候才会复用上次解析好的sqlParsedResult`，然而大部分ORM框架本身是不会对PreparedStatement进行缓存的，使用完之后就会关闭，然后释放连接，这样来说sql解析几乎每次都会重新做一次；

![image](https://cloud.githubusercontent.com/assets/4101682/19407931/260d4e3e-92e3-11e6-9205-5df13690742c.png)

可否像JDBC driver那样优化下，自己缓存PreparedStatement，然后才能真正意义上复用sql parse的结果；或者建立sql为key,sqlParsedResult为value的一个全局缓存，全局只需解析一次，以后任何statement都可以复用解析结果？

**Comment by hanahmily** [comment]
经过我们前期的压力测试，大约70个列的超长select语句的解析不会超过50ms，当然这是在一台hp的pc服务器上获得的结果。大部分sql语句都不会这么长，故我们觉得对解析结果的缓存也不太会加快整个流程。所以你说的很解析很耗时这个问题，能进一步举例来说明吗？
当然，如果前面的假设被认为是错误的，是可以增加你说的那种缓存方案的。需要关注retention的相关问题就可以了。

**Comment by yuanwhy** [comment]
项目中的sharding-jdbc-example-jdbc的第一个printSimpleSelect的sql语句 `SELECT i.* FROM t_order o JOIN t_order_item i  ON o.order_id=i.order_id WHERE o.user_id=? AND o.order_id=?` 解析就比较慢，我在mac pro上执行解析需要200ms左右，我改成run模式，log为info级别，计算的时间也没低于170ms，这种比较复杂的sql可能实际生产环境中不太常见，按照上面的说法，可能确实不用太关心；后续有优化会持续关注，谢谢解答 @hanahmily
