### ISSUE TITLE
Limit开始偏移量问题

### ISSUE THREAD

**Issue by yangyongh** [dangdangdotcom/sharding-jdbc#158]
根据一个字段分库、分表，两个库，每个库两个表的情况。
在使用分片字段分页查询时，开始偏移量总是0是什么问题？我看了在issues #79中有提到说Limit查询开始偏移量都是从0开始的。这个有方案实现正常分页查询吗？
我的查询语句如下：
分片字段为：column_0， 库分为db_0和db_1，db_0包含：t_table_0和t_table_1 , db_1包含：t_table_0和t_table_1。
select column_1,column_2 from t_table where column_0 in (1,2,3) limit 10,20;
查询结果是四个表0~20的数据，而不是10~20的数据集。

**Comment by yangyongh** [comment]
调试日志如下：
`11:43:47.400 [http-nio-8080-exec-7] DEBUG o.m.s.t.SpringManagedTransaction - JDBC Connection [com.dangdang.ddframe.rdb.sharding.jdbc.ShardingConnection@71aa558c] will not be managed by Spring
11:43:47.400 [http-nio-8080-exec-7] DEBUG c.s.l.s.dao.FaultLogDAO.getFaultLogs - ==>  Preparing: select * from b_fault_log WHERE device_id in (5,6,7,8,9,10,12,13,14) limit ?,? 
11:43:47.401 [http-nio-8080-exec-7] DEBUG c.s.l.s.dao.FaultLogDAO.getFaultLogs - ==> Parameters: 5(Integer), 20(Integer)
11:43:47.401 [http-nio-8080-exec-7] DEBUG c.d.d.r.s.parser.SQLParserFactory - Logic SQL: select * from b_fault_log WHERE  device_id in (5,6,7,8,9,10,12,13,14) limit ?,?
11:43:47.401 [http-nio-8080-exec-7] DEBUG c.d.d.r.s.parser.SQLParseEngine - Parsed SQL result: SQLParsedResult(routeContext=RouteContext(tables=[Table(name=b_fault_log, alias=Optional.absent())], sqlStatementType=null, sqlBuilder=null), conditionContexts=[ConditionContext(conditions={Condition.Column(columnName=device_id, tableName=b_fault_log)=Condition(column=Condition.Column(columnName=device_id, tableName=b_fault_log), operator=IN, values=[5, 6, 7, 8, 9, 10, 12, 13, 14], valueIndices=[])})], mergeContext=MergeContext(orderByColumns=[], groupByColumns=[], aggregationColumns=[], limit=Limit(offset=5, rowCount=20, offsetParameterIndex=Optional.of(0), rowCountParameterIndex=Optional.of(1))))
11:43:47.401 [http-nio-8080-exec-7] DEBUG c.d.d.r.s.parser.SQLParseEngine - Parsed SQL: SELECT * FROM [Token(b_fault_log)] WHERE device_id IN (5, 6, 7, 8, 9, 10, 12, 13, 14) LIMIT ?, ?
11:43:47.402 [http-nio-8080-exec-7] DEBUG c.d.d.r.s.router.SQLRouteEngine - final route result:[SQLExecutionUnit(dataSource=ds1, sql=SELECT * FROM b_fault_log_0 WHERE device_id IN (5, 6, 7, 8, 9, 10, 12, 13, 14) LIMIT ?, ?, sqlBuilder=SELECT * FROM [Token(b_fault_log_0)] WHERE device_id IN (5, 6, 7, 8, 9, 10, 12, 13, 14) LIMIT ?, ?), SQLExecutionUnit(dataSource=ds1, sql=SELECT * FROM b_fault_log_1 WHERE device_id IN (5, 6, 7, 8, 9, 10, 12, 13, 14) LIMIT ?, ?, sqlBuilder=SELECT * FROM [Token(b_fault_log_1)] WHERE device_id IN (5, 6, 7, 8, 9, 10, 12, 13, 14) LIMIT ?, ?), SQLExecutionUnit(dataSource=ds0, sql=SELECT * FROM b_fault_log_0 WHERE device_id IN (5, 6, 7, 8, 9, 10, 12, 13, 14) LIMIT ?, ?, sqlBuilder=SELECT * FROM [Token(b_fault_log_0)] WHERE device_id IN (5, 6, 7, 8, 9, 10, 12, 13, 14) LIMIT ?, ?), SQLExecutionUnit(dataSource=ds0, sql=SELECT * FROM b_fault_log_1 WHERE device_id IN (5, 6, 7, 8, 9, 10, 12, 13, 14) LIMIT ?, ?, sqlBuilder=SELECT * FROM [Token(b_fault_log_1)] WHERE device_id IN (5, 6, 7, 8, 9, 10, 12, 13, 14) LIMIT ?, ?)]
11:43:47.402 [http-nio-8080-exec-7] DEBUG c.d.d.r.s.router.SQLRouteEngine - merge context:MergeContext(orderByColumns=[], groupByColumns=[], aggregationColumns=[], limit=Limit(offset=5, rowCount=20, offsetParameterIndex=Optional.of(0), rowCountParameterIndex=Optional.of(1)))
11:43:47.404 [http-nio-8080-exec-7] DEBUG c.d.d.r.s.m.ShardingResultSets$WrapperResultSet - 790383559 join pipeline
11:43:47.405 [http-nio-8080-exec-7] DEBUG c.d.d.r.s.m.ShardingResultSets$WrapperResultSet - 241388400 join pipeline
11:43:47.405 [http-nio-8080-exec-7] DEBUG c.d.d.r.s.m.ShardingResultSets$WrapperResultSet - 1146082875 join pipeline
11:43:47.405 [http-nio-8080-exec-7] DEBUG c.d.d.r.s.m.ShardingResultSets$WrapperResultSet - 1357792754 join pipeline
11:43:47.405 [http-nio-8080-exec-7] DEBUG c.d.d.r.s.merger.ResultSetFactory - Sharding-JDBC: Sharding result sets type is 'MULTIPLE'
11:43:47.405 [http-nio-8080-exec-7] DEBUG c.d.d.r.s.m.p.r.IteratorReducerResultSet - 501313115 join pipeline
11:43:47.405 [http-nio-8080-exec-7] DEBUG c.d.d.r.s.m.p.c.LimitCouplingResultSet - 164466268 join pipeline
11:43:47.409 [http-nio-8080-exec-7] DEBUG c.s.l.s.dao.FaultLogDAO.getFaultLogs - <==      Total: 20
11:43:47.410 [http-nio-8080-exec-7] DEBUG org.mybatis.spring.SqlSessionUtils - Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@530919b6]`

**Comment by hanahmily** [comment]
limit 10,20的意思是偏移量从10开始 取20条数据。所以返回20条数据是正常的。每个分片在提取数据的时候偏移量是从0开始的，但是sjdbc会自动从第10条数据开始输出，然后输出20调数据。
如果你觉得有困难，可以把每个sql的数据贴出来，然后再对比最终结果观察一下。

**Comment by yangyongh** [comment]
谢谢，谢谢！
是我的错误，我混淆了limit的用法。

**Comment by life300131** [comment]
这个我也有疑惑，后来明白了为什么这么多，这个sharding-jdbc的新版本做了一个优化，在单库单表查询的时候，是正常的limit
