### ISSUE TITLE
结果集归并的时候可以采用堆排序来提升性能

### ISSUE THREAD

**Issue by starmarine** [dangdangdotcom/sharding-jdbc#161]
参考源码StreamingOrderByReducerResultSet.java
假如有10库，每库100表，取50个结果
如果采用遍历就是每次遍历1000个resultset，50个结果就是50000次
使用堆排序的话初始化时n_logn = 10000
剩下的50次就是50_logn = 500
总共10500次，还是有不小的性能提升

**Comment by terrymanu** [comment]
duplicate with #215
