### ISSUE TITLE
获取自增序列SQL实现

### ISSUE THREAD

**Issue by hanahmily** [dangdangdotcom/sharding-jdbc#164]
使用
```sql
SELECT LAST_INSERT_ID();
```
获取自增序列

**Comment by terrymanu** [comment]
已可以使用getGeneratedKeys的标准做法代替LAST_INSERT_ID()，不建议使用LAST_INSERT_ID()这样的非标准化SQL

**Comment by lanmo** [comment]
如果使用mybatis 标签使用
useGeneratedKeys="true" keyProperty="id"
并不能获取到自增的主键id值
