### ISSUE TITLE
读写分离 不进行分库分表

### ISSUE THREAD

**Issue by maojiawei** [dangdangdotcom/sharding-jdbc#168]
我就想单独使用读写分离 不使用分库分表有没有这样的例子

**Comment by maojiawei** [comment]
MasterSlaveDataSource 我想单独使用这个数据源可以吗

**Comment by ethanlamzs** [comment]
<bean id="ds_master" class="org.apache.commons.dbcp.BasicDataSource" destroy-method="close">
        <property name="driverClassName" value="com.mysql.jdbc.Driver"/>
        <property name="url" value="jdbc:mysql://115.28.171.4:3306/ds_0"/>
        <property name="username" value="root"/>
        <property name="password" value="123456"/>
    </bean>
    
    <bean id="ds_slave" class="org.apache.commons.dbcp.BasicDataSource" destroy-method="close">
        <property name="driverClassName" value="com.mysql.jdbc.Driver"/>
        <property name="url" value="jdbc:mysql://115.28.171.4:3306/ds_1"/>
        <property name="username" value="root"/>
        <property name="password" value="123456"/>
    </bean>
        
    
    <rdb:master-slave-data-source id="dbtbl" master-data-source-ref="ds_master" slave-data-sources-ref="ds_slave" />
    
    
    <rdb:strategy id="databaseShardingStrategy" sharding-columns="user_id"  algorithm-expression="dbtbl"/>
    
    
    <rdb:strategy id="tableShardingStrategy" sharding-columns="order_id" 
           algorithm-class="com.dangdang.ddframe.rdb.sharding.example.jdbc.algorithm.SingleKeyModuloTableShardingAlgorithm"/>
    
    <rdb:data-source id="shardingDataSource">
        <rdb:sharding-rule data-sources="dbtbl">
            <rdb:table-rules>
                <rdb:table-rule logic-table="mock" actual-tables="mock" 
                      database-strategy="databaseShardingStrategy" />
            </rdb:table-rules>
        </rdb:sharding-rule>
    </rdb:data-source>

**Comment by hanahmily** [comment]
恩 这样应该可以了

**Comment by terrymanu** [comment]
只用读写分离的话，mysql的jdbc驱动com.mysql.jdbc.ReplicationDriver就支持

**Comment by maojiawei** [comment]
感谢回答
