### ISSUE TITLE
读写分离配置后slave初始化连接池是配置数的三倍

### ISSUE THREAD

**Issue by xiaoliqiang** [dangdangdotcom/sharding-jdbc#169]
配置读写分离后slave初始化连接数是配置数的三倍，请问是配置问题还是存在这个问题？

**Comment by hanahmily** [comment]
slave是的连接数是底层的连接池控制的，sjdbc没有做额外监控。如果还觉得有问题，可以将你的配置方式，还有你是如何观察连接数超过预期的提供出来

**Comment by hanahmily** [comment]
关闭 如有问题请发邮件组询问
