### ISSUE TITLE
ShardingValue，TableRule 少了很多方法，为啥，1.4.0的版本

### ISSUE THREAD

**Issue by gavenpeng** [dangdangdotcom/sharding-jdbc#175]
1 getLogicTable()
2 isDynamic()
。。。

ShardingValue
下面这些方法都没有，是我自己添加的。

public Collection<T> getValues(){
        return this.values;
    }

    public T getValue(){
        return this.value;
    }

    public Range<T> getValueRange(){
        return this.valueRange;
    }

**Comment by gavenpeng** [comment]
是通过lombok.Getter 来的？

**Comment by hanahmily** [comment]
对 是编译的时候自动生成的
