### ISSUE TITLE
批量执行Update返回值不准确

### ISSUE THREAD

**Issue by hanahmily** [dangdangdotcom/sharding-jdbc#180]
批量执行Update 返回执行条数不准确。返回数据的行数是真实的SQL执行，但按照`JDBC`的规范应该返回逻辑SQL的执行。目前在特定条件返回的数组会多。

**Comment by githublaohu** [comment]
这个我接了，能告诉我一个切入点吗？
然后这个问题是 因为分表问题造成的吗吗？

**Comment by githublaohu** [comment]
有没有重现代码？

**Comment by githublaohu** [comment]
好的，收到，我先把环境搭建好。 @hanahmily

**Comment by githublaohu** [comment]
我看了， PreparedStatementExecutor.executeBatch 到执行 sql语句，应该不是PreparedStatementExecutor.executeBatch的错，而是 路由生成sql的问题吧。

**Comment by githublaohu** [comment]
executeBatch 使用多线程执行，是不是会有问题，
如果 批处理 的语句有执行关系
比如  批处理 a是添加，b是查询。如果多线程执行，a添加比b查询执行慢，那不出现脏数据了？

**Comment by hanahmily** [comment]
PreparedStatement的batch的语句是预编译的，所以不会查询a是查询，b是添加。batch操作针对的是一个语句的，但是参数不同。这个问题的点应该是没错的。您可以再仔细看看

**Comment by githublaohu** [comment]
看了，把 PreparedStatement 的  executeBatch 后面的所有都看完了。
update操作的数据，是100%能得到了，也找到的，获得异步返回的代码，
所以感觉是  路由方面的错误。
我找时间，搭建测试。

**Comment by hanahmily** [comment]
好的，想好改造思路后，在这里回复一下，咱们讨论好方案再动手。谢谢

**Comment by githublaohu** [comment]
不好意思，终于忙过来了，
环境搭建好，已经在调试。问题感觉是定位到了。
这个星期应该可以出解决方案。

**Comment by githublaohu** [comment]
问题已经找到，是rote分sql。
`           PreparedStatement ps = conn.prepareStatement("update t_order set status = ? where order_id in (?,?,?,?)" );
           ps.setString( 1 , "lao" );
           ps.setInt( 2 , 1101 );
           ps.setInt( 3 , 1102 );
           ps.setInt( 4 , 1001 );
           ps.setInt( 5 , 1003 );`
应该是 分三条 sql 语句，然后分了四条出来了，有一条重复执行
