### ISSUE TITLE
对于非MySQL数据库解析的支持

### ISSUE THREAD

**Issue by gitdingw** [dangdangdotcom/sharding-jdbc#184]
java.lang.ClassCastException: com.dangdang.ddframe.rdb.sharding.parser.visitor.basic.mysql.MySQLDeleteVisitor cannot be cast to com.alibaba.druid.sql.dialect.oracle.visitor.

**Comment by hanahmily** [comment]
这样的目前还无法对Oracle做支持，我们目前的工作在重构Parser模块。故在重构之前不会对MySQL以外的数据库给与支持。敬请期待

**Comment by lyg123** [comment]
如果自己在sharding-jdbc上加oracle的支持，应该从哪里入手

**Comment by terrymanu** [comment]
已完成对其他数据库的基本支持。
