### ISSUE TITLE
根据主机的IP生成workerId的IdGenerator实现

### ISSUE THREAD

**Issue by hanahmily** [dangdangdotcom/sharding-jdbc#191]
IPWorkerIdIdGenerator：获取机器的二进制表示的后10位，设置成workerId。
列如：
机器的IP为192.168.1.108（C0. A8.01. 6C），二进制后十位为：00000001.01101100设置workerId为364。

**Comment by xydonne** [comment]
@hanahmily 已参考HostNameIdGenerator的修改，已提交PR。
