### ISSUE TITLE
根据HOSTNAME的数字尾缀获取workerId的IdGenerator

### ISSUE THREAD

**Issue by hanahmily** [dangdangdotcom/sharding-jdbc#192]
HostNameWorkerIdIdGenerator：根据机器名最后的数字编号获取workerId，如果线上机器命名有统一规范，建议使用此种方式

列如：机器的HostName为dangdang-db-sharding-dev-12，会截取最后的编号12作为workerId。

**Comment by xydonne** [comment]
已完成，用了PowerMock来mock模拟静态方法。
https://github.com/xydonne/sharding-jdbc/tree/id-generator/192

**Comment by hanahmily** [comment]
@xydonne 如果保证测试覆盖率没有下降 就可以提交pull request。我将在pr中做code review

**Comment by xydonne** [comment]
@hanahmily  新增内容，测试覆盖率100%，已提交PR。
