### ISSUE TITLE
关于spring+mybatis整合配置，插入时关于 dual表 出现的异常

### ISSUE THREAD

**Issue by BreakT** [dangdangdotcom/sharding-jdbc#193]
我使用bean的方式配置看sharding-jdbc 查询没有问题，但我在插入数据时，用到了
<selectKey keyProperty="id" resultType="java.lang.String" order="BEFORE">
	select concat('pb',lpad(nextval('seq_tbl_payment_base'),13,'0')) from dual
</selectKey>
类似这样的字符串拼接。
插入时，报：
![image](https://cloud.githubusercontent.com/assets/14869509/20515772/382bdf78-b0ce-11e6-9a07-17638b611d65.png)
这样的一个异常 我dual这个虚拟表应该在sharding-jdbc里怎么配置呢。
下面是我的配置文件：
![image](https://cloud.githubusercontent.com/assets/14869509/20515866/7da174fa-b0ce-11e6-89b4-b3fb7848a970.png)
![image](https://cloud.githubusercontent.com/assets/14869509/20515880/8d6b4a8c-b0ce-11e6-8093-21d3b5323890.png)
![image](https://cloud.githubusercontent.com/assets/14869509/20515900/9c59b3da-b0ce-11e6-88b5-e91e67af1cfb.png)
![image](https://cloud.githubusercontent.com/assets/14869509/20515908/a878e6ea-b0ce-11e6-972a-0e78e92b195e.png)
![image](https://cloud.githubusercontent.com/assets/14869509/20515920/b76d506e-b0ce-11e6-9688-135c0bdc4d0f.png)

**Comment by hanahmily** [comment]
目前不支持dual虚拟表这种情况

**Comment by BreakT** [comment]
奥 好的 谢谢您的解答

**Comment by hanahmily** [comment]
dual 表操作其实都是一些算法。作为sjdbc的定位来说不太适合去实现。而且也没有去实现函数的必要。这些操作应该在应用中去完成。
关于主键生成sjdbc已经实现，可以关注一下相关文档。
