### ISSUE TITLE
SQL功能增强

### ISSUE THREAD

**Issue by hanahmily** [dangdangdotcom/sharding-jdbc#195]
由于SQL语句种类繁多，目前sjdbc支持主流的SQL。但是会根据项目的发展逐步支持。
请在该issue下留言需要增加的SQL语句功能。

留言需要**详细描述**支持的形式，如果涉及**跨多数据库的操作**，请说明为什么该操作是必要的。

如果该SQL在其他中间件产品中（不论是开源还是商业）已经实现，请注明。该特性理论上可以获得较快的支持。

**Comment by hanahmily** [comment]
#93 提到这个功能，是将join于update组合。

[update](http://dev.mysql.com/doc/refman/5.7/en/update.html)文档描述该功能具体表现。

实现该功能可以依赖于select的实现。但该功能使用范围不大，优先级较低。

**Comment by terrymanu** [comment]
目前暂时不考虑太复杂的、面向OLAP的SQL
