### ISSUE TITLE
读写分离与分库分表配置独立

### ISSUE THREAD

**Issue by hanahmily** [dangdangdotcom/sharding-jdbc#196]
读写分离可以单独使用。

**建议的新功能行为**

配置读写分离后，不需要再配置ShardingRule。
可以单独配置读写分离。

**为什么这个新功能是对大多数用户有用的**

由于很多用户都是先进行读写分离，后进行分库分表，故该配置该改进符合这样的发展规律。

**Comment by limingwei** [comment]
是的 是的 是的

**Comment by terrymanu** [comment]
fixed at 1.6.0
