### ISSUE TITLE
测试在批量插入时，分表完全没有规则了，是乱的。

### ISSUE THREAD

**Issue by gavenpeng** [dangdangdotcom/sharding-jdbc#198]
//通过ibatis 这样写，opLogsAnalyses 是一个list
oplogIbaitsDAO.batchInsert("monitor_oplog_analyse.insertOpLog", opLogsAnalyses);

插入数据库的结果就不分了。在单个插入是可以的。

**Comment by hanahmily** [comment]
issue不接受帮助问题 请将配置问价 日志发到邮件组中
