### ISSUE TITLE
分表且复用PreparedStatement对象造成数据路由错误

### ISSUE THREAD

**Issue by hanahmily** [dangdangdotcom/sharding-jdbc#199]
分表场景下，复用PreparedStatement对象 或者 使用batch方法

**问题复现步骤:**

1.  只分表
1.  复用PreparedStatement
```java
PreparedStatement ps = shardingConnection.prepareStatement(.....)
...
...
ps.execute();
...
...
ps.execute()
```

1.  或使用batch接口
```java
...
ps.addBatch();
...
...
ps.addBatch();
ps.executeBatch();
```

**期望的表现:**

数据像日志预期的那样插入到指定的表

**观察到的表现:**

数据全插入了第一次路由到的表，后续的表不插入

**Sharding-JDBC版本:** [1.4.0]
**操作系统及版本:** [OSX]

**Comment by ben1247** [comment]
赞一个～
