### ISSUE TITLE
一个大表，拆分为100个小表，应该怎么做？

### ISSUE THREAD

**Issue by frank-liu-1** [dangdangdotcom/sharding-jdbc#204]
如果分为N个表，那么配置文件里如下
t_order_0, t_order_1,t_order_2 需要把所有的表名字一一列出来。

我公司的项目是某些表不分表，某些表要分100张表，比如t_order_0~t_order_99
怎么做？ 不可能把这100个表名字全部都写在xml配置文件里。
我能想到的， 就是把这个bean做成InitializingBean，在afterPropertiesSet(){}里面进行set这个table name的list
我想问的是，  能不能，仅仅设置表名的前缀，比如tablePrefix  和tableCount ,这样表名的配置会简单的多。

**Comment by hanahmily** [comment]
部分表的项目可以使用默认数据源。配置ShardingRule的时候有一个参数可以配置某一个数据源是默认数据源。

使用spring的配置 配置actual-table的时候可以用inline表达式：t_order${0..99}。这样100张表就配置好了。

最后 目前issue不接受问题咨询了。如果有问题可以加qq全，或发送邮件到sharding_jdbc@groups.163.com

**Comment by frank-liu-1** [comment]
多谢。
