### ISSUE TITLE
路由到单库单表移除补充的SQL语句片段

### ISSUE THREAD

**Issue by hanahmily** [dangdangdotcom/sharding-jdbc#210]
Sharing-JDBC会在order by，group by 等语句中对原始的sql进行改造，增加一些而外的内容。
但是在最终路由结果为单库单表时，这些增加的SQL片段就是一些多余的内容。

**建议的新功能行为**

在最终结果为单库单表时，去掉这些增加的内容。

**为什么这个新功能是对大多数用户有用的**

这个功能对性能的提升有帮助，同时可以帮助一些有子查询的遗留系统

**Comment by StormAll** [comment]
正在处理此issue
大致修改思路：
1、在SQLBuilder中对SQL片段增加是否是额外增加的标识
2、在SQLRouteEngine的routeSQL方法，根据路由结果，处理额外增加的SQL片段
