### ISSUE TITLE
1.3.1版本 表名前加库名查询报空指针

### ISSUE THREAD

**Issue by lulonglong** [dangdangdotcom/sharding-jdbc#212]
select * from dbname.tablename;
表名前加库名会报空指针。原生jdbcTemplate正常运行。
版本是1.3.1，在后续版本已修复请忽略。
若没修复建议进行修复，保持与原生jdbcTemplate的无缝切换。

**Comment by hanahmily** [comment]
sjdbc的dbname代表的是shardingrule中配置的datasourcerule名字，也就是那个map映射的名字。并不是数据库schema的名字。
另外，这个地方的bug在于对于这种错误提示不友好，并应该抛出空指针异常，而是应该抛出更有意义的异常。
