### ISSUE TITLE
spring事务失效的BUG

### ISSUE THREAD

**Issue by biakia** [dangdangdotcom/sharding-jdbc#213]
1、现象
最近使用Sharding-JDBC做数据层，上层使用Mybatis做ORM，使用Spring声明式事务控制本地事务，在实际使用中发现在同一个库下执行多条sql，spring事务控制没有生效。
2、原因分析
Sharding-JDBC的ShardingConnection会包含多个真实数据源的Connection，ShardingConnection会在真正执行sql语句的时候才会去获取Connection然后缓存起来，这其实是一种懒加载。如果我们在真正执行sql之前去setAutoCommit=false，这时候由于真实的Connection还没有获取，所以这个操作是无效的。后续所有执行的sql都不受事务控制。而spring在做事务控制的时候其实是基于ShardingConnection的，当spring去setAutoCommit=false的时候，其实并没有生效，这也是spring事务失效的根本原因。
3、临时解决方案
首先是要Mybatis的SqlSessionFactory获取一个SqlSession，然后根据SqlSession拿ShardingConnection，然后根据分片策略拿到真实的Connection，最后基于真实的Connection去做JDBC层面的事务控制

**Comment by haocao** [comment]
AbstractConnectionAdapter中会记录setAutoCommit动作，当ShardingConnection调用getConnection方法时会进行动作回放。

    @Override
    public final void setAutoCommit(final boolean autoCommit) throws SQLException {
        this.autoCommit = autoCommit;
        if (getConnections().isEmpty()) {
            recordMethodInvocation(Connection.class, "setAutoCommit", new Class[] {boolean.class}, new Object[] {autoCommit});
            return;
        }
        for (Connection each : getConnections()) {
            each.setAutoCommit(autoCommit);
        }
    }

可以试一下sharding-jdbc-example-mybatis这个项目，场景应该和你是一样的，可以支持Spring事务控制。 AbstractConnectionAdapter中会记录setAutoCommit动作，当ShardingConnection调用getConnection方法时会进行动作回放。

    @Override
    public final void setAutoCommit(final boolean autoCommit) throws SQLException {
        this.autoCommit = autoCommit;
        if (getConnections().isEmpty()) {
            recordMethodInvocation(Connection.class, "setAutoCommit", new Class[] {boolean.class}, new Object[] {autoCommit});
            return;
        }
        for (Connection each : getConnections()) {
            each.setAutoCommit(autoCommit);
        }
    }

可以试一下sharding-jdbc-example-mybatis这个项目，场景应该和你是一样的，可以支持Spring事务控制。

**Comment by biakia** [comment]
经过测试，ShardingConnection确实支持事务，之前测试有问题是因为Spring事务配置有问题，谢谢！
