### ISSUE TITLE
SpringShardingDataSource 可以暴露 ShardingRule、ShardingConfig 等属性

### ISSUE THREAD

**Issue by gfreezy** [dangdangdotcom/sharding-jdbc#222]
现在没办法拿到解析后的配置和对应的数据源，所以无法实现自动在多个数据源创建表。

**Comment by hanahmily** [comment]
这些信息目前都是内部使用，我们不建议使用这些信息去创建表。而且sjdbc的理念就是轻量级的，ddl操作应该使用运维手动去实现，而不是使用程序去实现
