### ISSUE TITLE
非配置多键数据库分片错误

### ISSUE THREAD

**Issue by himayun** [dangdangdotcom/sharding-jdbc#235]
规则设定代码：
DataSourceRule dataSourceRule = new DataSourceRule(createDataSourceMap()); TableRule orderTableRule = TableRule.builder("t_pos_trade_bill").actualTables(Arrays.asList("t_pos_trade_bill_0", "t_pos_trade_bill_1")).dataSourceRule(dataSourceRule).build(); //TableRule orderItemTableRule = TableRule.builder("t_order_item").actualTables(Arrays.asList("t_order_item_0","t_order_item_1")).dataSourceRule(dataSourceRule).build(); ShardingRule shardingRule =ShardingRule.builder().dataSourceRule(dataSourceRule).tableRules(Arrays.asList(orderTableRule)) .bindingTableRules(Collections.singletonList(new BindingTableRule(Arrays.asList(orderTableRule)))) .databaseShardingStrategy(**new DatabaseShardingStrategy("vbill_no,vcreate_date",** new ModuloDatabaseShardingAlgorithm())).tableShardingStrategy(new TableShardingStrategy( "vbill_no,vcreate_date" , new ModuloTableShardingAlgorithm())).build();

//这段为动态注入到spring容器中,做个测试
    GenericBeanDefinition definition = new GenericBeanDefinition();
    definition.setBeanClass(ShardingDataSource.class);
    ConstructorArgumentValues values = new ConstructorArgumentValues();
    values.addIndexedArgumentValue(0,shardingRule);
    definition.setConstructorArgumentValues(values);
    beanDefinitionRegistry.registerBeanDefinition("myDataSource",definition);

**错误日志：**

[DEBUG] 2017-03-23 19:30:33,432 --DubboServerHandler-192.168.0.77:20882-thread-2-- [com.dangdang.ddframe.rdb.sharding.parser.SQLParserFactory] Logic SQL: INSERT INTO  t_pos_trade_bill (ncreator,nsell_member_id,nnow_money,vactivity_ids,vis_synch,vbill_no,vstatus,vpayment_type,npaid_money,vmachine_id,nbuy_member_id,vis_network_cashier,vcreate_date) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?), [1, 1, 0.200000000000000011102230246251565404236316680908203125, 1, 5, JImXTbU7, 561, A, 3, He8M2SAa, 2, 5, 20170323193033] 
[DEBUG] 2017-03-23 19:30:33,533 --DubboServerHandler-192.168.0.77:20882-thread-2-- [com.dangdang.ddframe.rdb.sharding.parser.SQLParseEngine] Parsed SQL result: SQLParsedResult(routeContext=RouteContext(tables=[Table(name=t_pos_trade_bill, alias=Optional.absent())], sqlStatementType=null, sqlBuilder=null), generatedKeyContext=GeneratedKeyContext(columns=[], columnNameToIndexMap={}, valueTable={}, rowIndex=0, columnIndex=0, autoGeneratedKeys=0, columnIndexes=null, columnNames=null), conditionContexts=[ConditionContext(conditions={})], mergeContext=MergeContext(orderByColumns=[], groupByColumns=[], aggregationColumns=[], limit=null)) 
[DEBUG] 2017-03-23 19:30:33,536 --DubboServerHandler-192.168.0.77:20882-thread-2-- [com.dangdang.ddframe.rdb.sharding.parser.SQLParseEngine] Parsed SQL: INSERT INTO [Token(t_pos_trade_bill)] (ncreator, nsell_member_id, nnow_money, vactivity_ids, vis_synch , vbill_no, vstatus, vpayment_type, npaid_money, vmachine_id , nbuy_member_id, vis_network_cashier, vcreate_date) VALUES (?, ?, ?, ?, ? , ?, ?, ?, ?, ? , ?, ?, ?) 
[DEBUG] 2017-03-23 19:30:33,541 --DubboServerHandler-192.168.0.77:20882-thread-2-- [com.dangdang.ddframe.rdb.sharding.router.single.SingleTableRouter] Before database sharding t_pos_trade_bill routes db names: [ds_0, ds_1] sharding columns: [vbill_no,vcreate_date] sharding values: [] 

分片数据库代码：
public final class ModuloDatabaseShardingAlgorithm implements SingleKeyDatabaseShardingAlgorithm<String> {
    

    public String doEqualSharding(final Collection<String> dataSourceNames, final ShardingValue<String> shardingValue) {
        for (String each : dataSourceNames) {
            int l = shardingValue.getValue().hashCode() % 2;
            if (each.endsWith(l+"")) {
                return each;
            }
        }
        throw new IllegalArgumentException();
    }

    public Collection<String> doInSharding(final Collection<String> dataSourceNames, final ShardingValue<String> shardingValue) {
        Collection<String> result = new LinkedHashSet(dataSourceNames.size());
        for (String value : shardingValue.getValues()) {
            for (String dataSourceName : dataSourceNames) {
                if (dataSourceName.endsWith(value.hashCode() % 2 + "")) {
                    result.add(dataSourceName);
                }
            }
        }
        return result;
    }

    public Collection<String> doBetweenSharding(final Collection<String> dataSourceNames, final ShardingValue<String> shardingValue) {
        Collection<String> result = new LinkedHashSet(dataSourceNames.size());

        return result;
    }
}

**Comment by cr6588** [comment]
你都使用多键数据库分片为何ModuloDatabaseShardingAlgorithm实现的是SingleKeyDatabaseShardingAlgorithm接口，应该是MultipleKeysDatabaseShardingAlgorithm

**Comment by terrymanu** [comment]
如果是配置错误导致的话，issue我先关了，如还有问题请再开启和讨论
