### ISSUE TITLE
批量插入有bug

### ISSUE THREAD

**Issue by ddyycao** [dangdangdotcom/sharding-jdbc#236]
文档里说不支持批量insert语句，但是我测试了下是可以执行的，而且只会根据第一条数据路由
比如：
insert into `ref` ( `ID`, `ref_value`, `b_id`) 
values( '11000211', 'ref valuex', 1000250), ( '11000111', 'ref valuex1', 1000100)
会插入到一个表里，实际上1000250和1000100会路由到不同的表

**Comment by terrymanu** [comment]
文档已明确说明不支持。承诺范围之外的东西限于精力暂时不会做。
