### ISSUE TITLE
数据源加载出现double情况

### ISSUE THREAD

**Issue by lijiahuioooo** [dangdangdotcom/sharding-jdbc#237]
data-source指定数据源会被初始化成内部bean， sharding-jdbc 是使用这个内部bean作为数据源，外层设定数据源bean没有被用，这就造成 数据源会被初始化两次 也就是启动时 会有两套同样的数据源 都加载了

排查原因：
 Map<String, BeanDefinition> result = new ManagedMap<>(dataSources.size());

value 使用了 BeanDefinition 类型
spring 解析 ManagedMap 类型代码

else if (value instanceof ManagedMap) {
			// May need to resolve contained runtime references.
			return resolveManagedMap(argName, (Map<?, ?>) value);
		}

private Map<?, ?> resolveManagedMap(Object argName, Map<?, ?> mm) {
		Map<Object, Object> resolved = new LinkedHashMap<Object, Object>(mm.size());
		for (Map.Entry<?, ?> entry : mm.entrySet()) {
			Object resolvedKey = resolveValueIfNecessary(argName, entry.getKey());
			Object resolvedValue = resolveValueIfNecessary(
					new KeyedArgName(argName, entry.getKey()), entry.getValue());
			resolved.put(resolvedKey, resolvedValue);
		}
		return resolved;
	}

value 最后重新调用 resolveValueIfNecessary方法

解析
else if (value instanceof BeanDefinition) {
			// Resolve plain BeanDefinition, without contained name: use dummy name.
			BeanDefinition bd = (BeanDefinition) value;
			String innerBeanName = "(inner bean)" + BeanFactoryUtils.GENERATED_BEAN_NAME_SEPARATOR +
					ObjectUtils.getIdentityHexString(bd);
			return resolveInnerBean(argName, innerBeanName, bd);
		}

BeanDefinition类型会直接生成内部bean ，没有使用外部bean作为数据源；

这种情况配置bean数据源就会被加载两套 内部bean一套，外部bean 一套  sharding-jdbc使用的是内部bean作为数据源，外部bean数据源没有用

**Comment by drtrang** [comment]
我也遇到了同样的问题，补充一下场景。

代码中手动声明了 `dataSourceMap`，Map 里存放了所有的 DataSource，但是在创建 `dataSource` 时并没有注入我声明的 `dataSourceMap`，而是使用的 Spring 自身生成的 Map。
```java
@Bean
@ConfigurationProperties("spring.datasource.druid.huanan")
public DruidDataSource huananDataSource() {
    return new DruidMultiDataSource();
}

@Bean
@ConfigurationProperties("spring.datasource.druid.xinan")
public DruidDataSource xinanDataSource() {
    return new DruidMultiDataSource();
}

@Bean
@Primary
public Map<String, DataSource> dataSourceMap(List<DruidDataSource> druidDataSourceList) {
    // 该 Bean 没有初始化
    return druidDataSourceList.stream()
            .collect(Collectors.toMap(DruidDataSource::getName, Function.identity()));
}

@Bean
@Primary
public DataSource dataSource(Map<String, DataSource> dataSourceMap, DatabaseShardingStrategy databaseShardingStrategy) {
    // 这里的 dataSourceMap 并不是上面声明的 Map，而是 Spring 自己生成的
    DataSourceRule dataSourceRule = new DataSourceRule(dataSourceMap, "common");
    TableRule housedelTableRule = createTableRule("sh_housedel", dataSourceRule);
    List<TableRule> tableRules = Arrays.asList(housedelTableRule);
    ShardingRule shardingRule = ShardingRule.builder()
            .dataSourceRule(dataSourceRule)
            .tableRules(tableRules)
            .databaseShardingStrategy(databaseShardingStrategy)
            .build();
    return ShardingDataSourceFactory.createDataSource(shardingRule);
}
```

**Comment by beibeii** [comment]
这个bug会把机器内存吃光，oom

**Comment by terrymanu** [comment]
即使是加载了两次，也不会oom。请问oom是如何定位的？ @beibeii

**Comment by terrymanu** [comment]
好像是你自定义java config的问题？因为这里并未用到spring namespace，因此这是两个不同的场景。
如果仍然有问题，欢迎新提交一个issue。 @drtrang

**Comment by drtrang** [comment]
@terrymanu  恩，是 Spring 的问题，跟 SJ 没关系。

**Comment by terrymanu** [comment]
fixed at 1.5.3
