### ISSUE TITLE
sharding-jdbc会默认把类似于T.ID或T.id修改为t.id

### ISSUE THREAD

**Issue by shanleiyang** [dangdangdotcom/sharding-jdbc#238]
sharding-jdbc会默认把类似于T.ID或T.id修改为t.id，如果设置mysql大小写敏感并且sql语句中别名都写为大写时，则会引起报错：com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Unknown column 't.id' in 'field list'

**Comment by yuanwhy** [comment]
新版本好像没这个问题

**Comment by terrymanu** [comment]
1.5.0.M1应该已经解决了，先关闭了，如果仍有问题欢迎反馈
