### ISSUE TITLE
CommonSelfIdGenerator最后四位不是随机的

### ISSUE THREAD

**Issue by beston123** [dangdangdotcom/sharding-jdbc#241]
CommonSelfIdGenerator.java中Id，毫秒内自增值不是随机的，
对于 ‘id%分表数’ 这样的分表规则，数据分布不均匀。
>    
    public synchronized Number generateId() {
        long time = clock.millis();
        Preconditions.checkState(lastTime <= time, "Clock is moving backwards, last time is %d milliseconds, current time is %d milliseconds", lastTime, time);
        if (lastTime == time) {
            if (0L == (sequence = ++sequence & SEQUENCE_MASK)) {
                time = waitUntilNextTime(time);
            }
        } else {
            sequence = 0;
        }
        lastTime = time;
        if (log.isDebugEnabled()) {
            log.debug("{}-{}-{}", new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS").format(new Date(lastTime)), workerId, sequence);
        }
        return ((time - SJDBC_EPOCH) << TIMESTAMP_LEFT_SHIFT_BITS) | (workerId << WORKER_ID_LEFT_SHIFT_BITS) | sequence;
    }

建议修改 sequence = new Random().newInt(1024);

**Comment by terrymanu** [comment]
这里采用的是snowflake算法。我们暂时不打算对其算法本身进行改写。
