### ISSUE TITLE
1.4.2版本 CASE WHEN EXISTS的时候 无法set parameters

### ISSUE THREAD

**Issue by ManderLS** [dangdangdotcom/sharding-jdbc#245]
RT： 
SELECT  CASE WHEN EXISTS(SELECT id FROM  da_3d_bill_type  WHERE parent_id=?) THEN 1 ELSE 0 END AS haschild FROM DUAL
此时报set失败   1.3.1版本是好使的

**Comment by terrymanu** [comment]
不支持子查询
