### ISSUE TITLE
如何配置只分库，不分表

### ISSUE THREAD

**Issue by zhuchao941** [dangdangdotcom/sharding-jdbc#246]
``` java
	public DataSource initDataSource() {
		// List<TableRule> list = new ArrayList<>();
		// list.add(TableRule.builder("order").actualTables(Lists.newArrayList("order")).build());
		Map<String, DataSource> map = new HashMap<>();
		map.put("shard1", shard1());
		map.put("shard2", shard2());
		DataSourceRule dataSourceRule = new DataSourceRule(map);
		ShardingRule shardingRule = ShardingRule.builder()
				.dataSourceRule(dataSourceRule)
				.databaseShardingStrategy(new DatabaseShardingStrategy("shardx", new ModuloTableShardingAlgorithm()))
        .build();
		return ShardingDataSourceFactory.createDataSource(shardingRule);
	}
```
上述方式会造成 SingleTableRouter  构造函数直接报异常：
Cannot find table rule and default data source with logic table

跟踪源码发现貌似也没有哪处显示可以不走TableRouter的，还望各位大大指教

另外我还有个思路，那就是走TableRouter，只是都分到同一个物理分片上

第一天学习，望各位指教

**Comment by dale19900108** [comment]
在构建shardingRule的时候，你的这种情况就不用使用databaseShardingStrategy了。直接用tableRule就可以 。类似于这样子
`ShardingRule shardingRule = ShardingRule.builder()
                .dataSourceRule(getDataSourceRule())
                .tableRules(Arrays.asList(orderTableRule,ticketTableRule))
                .build();`

**Comment by zhuchao941** [comment]
@dale19900108 你说的这个我从文档里完全无法读出来。我的理解是 databaseShardingStrategy 只是 分库策略，而TableShardingStrategy才是分表策略。所以能劳烦大致讲下这个结构，或者给贴个有用的链接否？

**Comment by dale19900108** [comment]
@zhuchao941 ,http://dangdangdotcom.github.io/sharding-jdbc/02-guide/sharding/

**Comment by dale19900108** [comment]
@zhuchao941 你说的那个我的理解是 databaseShardingStrategy 是 分库策略，而TableShardingStrategy才是分表策略，这个是正确的，没异议。你的实际需要是不需要分库分表，所以就不用配置这两个。

**Comment by zhuchao941** [comment]
@dale19900108 不对吧，我的需求没有分表，但是有分库啊，TableRule到底是怎么样的定位呢

**Comment by zhuchao941** [comment]
并且昨天看的时候，我发现在构建ShardingRule这个的时候，既有databaseShardingStrategy，但是TableRule里也有databaseShardingStrategy。这又是什么规则

**Comment by dale19900108** [comment]
我也是准备用这个中间件。昨天开始的尝试学习使用的。这两个策略应该是api都相同。所以混用了也没事。但是容易引起歧义，我是这么理解的。

**Comment by dale19900108** [comment]
你的需求跟我差不多哎，都是没分表，相当于新起个数据库跟原来一样。想做两个数据库的联合查询。对吧 。

**Comment by zhuchao941** [comment]
@dale19900108 倒是不用联合，只是分库，不做分表。那咱们起步差不多么。。哈哈

**Comment by dale19900108** [comment]
@zhuchao941  ，私聊我下，一起研究下呗？

**Comment by chubinzheng** [comment]
tableRuleList.add(new TableRule.TableRuleBuilder("t_order").actualTables(Arrays.asList("t_order")).dataSourceRule(dataSourceRule).build());
这是我的实现方式。只分库不分表

**Comment by terrymanu** [comment]
问题已解决，issue先关了，有需要请再开
