### ISSUE TITLE
频繁查询时，使用Sharding-JDBC出现RejectedExecutionException

### ISSUE THREAD

**Issue by ybshen** [dangdangdotcom/sharding-jdbc#247]
感觉像是一次查询没有结束，第二次查询就会报下面的错误，不知道是什么原因？谢谢！
java.util.concurrent.RejectedExecutionException: Task com.google.common.ut
il.concurrent.ListenableFutureTask@44c0c9be rejected from java.util.concur
rent.ThreadPoolExecutor@52a951aa[Running, pool size = 100, active threads
= 99, queued tasks = 0, completed tasks = 1713]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExe
cution(ThreadPoolExecutor.java:2047)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecut
or.java:823)
        at java.util.concurrent.Executors$DelegatedExecutorService.execute
(Executors.java:668)
        at com.google.common.util.concurrent.MoreExecutors$ListeningDecora
tor.execute(MoreExecutors.java:484)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExe
cutorService.java:134)
        at com.google.common.util.concurrent.AbstractListeningExecutorServ
ice.submit(AbstractListeningExecutorService.java:58)
        at com.dangdang.ddframe.rdb.sharding.executor.ExecutorEngine.submi
tFutures(ExecutorEngine.java:105)

**Comment by terrymanu** [comment]
sjdbc有配置可以配置执行连接池的size，请根据实际需求调整这个值
