### ISSUE TITLE
查询物理分页时有BUG,查询结果不分页

### ISSUE THREAD

**Issue by jianbinJava** [dangdangdotcom/sharding-jdbc#248]
举例: 订单表 order_info , 订单分表  order_info_01 (有数据), order_info_02(没数据) ,
查询SQL :  select * from order_info order by id desc limit 10,10 ;
sharding-jdbc 发出的 sql 为查询两张分表, 在查询结果归并的时候,被识别为单表命中. 打印的日志内容为:  Sharding-JDBC: Sharding result sets type is 'SINGLE' , 在该类型下,结果返回时没有做物理分页的处理,直接把所有结果返回. 结果导致分页无效,返回全部数据.

**Comment by boothsun** [comment]
遇到同样问题，很坑呀

**Comment by terrymanu** [comment]
duplicate with #239

**Comment by terrymanu** [comment]
fixed at 1.5.0.M2
