### ISSUE TITLE
mybatis batch update 异常

### ISSUE THREAD

**Issue by xuji1122** [dangdangdotcom/sharding-jdbc#249]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.4.2
### Expected behavior
batch update
### Actual behavior
java.sql.SQLException: Parameter index out of range (10 > number of parameters, which is 9).
### Steps to reproduce the behavior
1,mybatis mapper
![image](https://cloud.githubusercontent.com/assets/8310736/25942678/037ec84e-3670-11e7-8d3f-a24d6c5cbc4c.png)
2,hitmanager
![image](https://cloud.githubusercontent.com/assets/8310736/25942727/23d49ee8-3670-11e7-9a85-5d620744313c.png)

3,debug 打印结果
![image](https://cloud.githubusercontent.com/assets/8310736/25942778/46e1557a-3670-11e7-8589-d3c68650c970.png)
![image](https://cloud.githubusercontent.com/assets/8310736/25942792/575e4aca-3670-11e7-9e0b-c4ebbcdf1ca1.png)
![image](https://cloud.githubusercontent.com/assets/8310736/25942813/6317a32a-3670-11e7-8fde-450bf51e1392.png)

**Comment by terrymanu** [comment]
目前不支持一次执行多条SQL，未来版本也许会增加此功能。先关闭了，等有计划时再讨论
