### ISSUE TITLE
读写分离主从切换规则

### ISSUE THREAD

**Issue by cnderrick** [dangdangdotcom/sharding-jdbc#250]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
最新版本1.4.2
### Expected behavior
开启写事务时，先查询再写操作而后再查询，这一流程全部使用主库
### Actual behavior
在同一事务下，先查询用从库查询，而后的写和查询使用主库。

原本写事务前的判断应该是基于对主库数据确认需要修改后再决定增删改的业务。请问，目前框架有参数可配么，我是按照中文介绍里的主从设置配置的。感觉在某些业务场景下会有很大问题。

**Comment by terrymanu** [comment]
读写分离+事务这里我们确实没有仔细考虑过，未来需要好好梳理一下。
不过读写分离中，又读又写，还要在同一事务中似乎不可能，需要开启XA？这样性能又太受限制，因此需要讨论下如何实现比较好，还是读写分离就不应该支持事务？

**Comment by cnderrick** [comment]
@terrymanu  读库和写库间数据的同步存在一个时间差，某些写场景下修改数据前需要查询是否已存在或者不存在相关内容。如果走读库查询再删除主库数据会存在概率导致数据在极短时间内不一致；感觉你们在底层实现上应该是判断了sql的类型，然后决定走读库还是写库。在一个写事务前的查询走写库是否可以用注解声明下，毕竟jdbc的执行是在动态调用的时候才会知道，无法预知未来，通过一个标记位来告诉sharding-jdbc这里是特殊的逻辑，不过这样又跟sharding-jdbc的初衷相悖了，原本是要做一层透明的非侵入式底层框架，我也没有想到更成熟的实现提议仅供参考。目前我是在业务层做的逻辑处理，在写库代码中实现一套读写库逻辑，来解决这个问题。

您说的：“还是读写分离就不应该支持事务？”，我没太懂是会引发什么问题吗。

**Comment by terrymanu** [comment]
读写分离一定是在两个库。如果支持事务势必要开启XA。这样的性能还不如读写不分离，得不偿失。

**Comment by terrymanu** [comment]
目前sharding-jdbc的定位是柔性事务，因此读写分离的情况，开启在同一事务中不符合sharding-jdbc的前提条件。因此此issue先关闭了。
