### ISSUE TITLE
如何进行多库同一张表的汇总查询

### ISSUE THREAD

**Issue by zdzqianmu** [dangdangdotcom/sharding-jdbc#252]
当前count能够将两个库的条目进行汇总，
但是获取记录的时候只能获取到单条记录，但是返回的对象列表size为查询数量
List<T> list:
list.size=6
但是foreach的时候只能发现一个结果对象

**Comment by terrymanu** [comment]
count进行过结果归并，多少个库都会汇总到一个结果集，就像对单库操作一样。
我不知道是否正确的理解了你的问题？

**Comment by terrymanu** [comment]
长时间无反馈，先关闭了。
