### ISSUE TITLE
1.5.0-SNAPSHOOT 版本关于GOUP BY查询及对应COUNT统计的建议

### ISSUE THREAD

**Issue by jianbinJava** [dangdangdotcom/sharding-jdbc#257]
发现1.5.0 在分析SQL时如果碰到子查询直接抛出不支持子查询的异常.建议支持简单统计的子查询.
比如 我有个带聚合查询的SQL想统计聚合后的总量.
查询的SQL如下:
SELECT  order_id , count(money_rmbamt) as cnt_money_rmbamt FROM sdt_bill_info bi  WHERE xxx  GROUP BY order_id  ; 
对应统计该聚合函数的SQL如下:
SELECT COUNT(1) FROM (  SELECT  order_id  FROM sdt_bill_info bi  WHERE xxx  GROUP BY order_id     ) AS tm_t 
;
在该场景下的统计总数就不得不使用一个子查询来处理总行数.
该场景在1.4.2 版本上是支持的,
但是1.5.0-SNAPSHOOT 的当前版本未支持.希望也能够支持.

**Comment by terrymanu** [comment]
sjdbc从未承诺支持子查询，并且明确的在不支持列表中声明了不支持子查询。之前的1.4.2对子查询的支持仅仅是内部需求的hack。为了功能的清晰与统一，1.5.0仍然不支持子查询，因此这部分会从1.4.2的版本中删除。

**Comment by terrymanu** [comment]
在未来的版本会全面的支持子查询，但由于版本发布时间的问题，此项更新不会在1.5.0发布
