### ISSUE TITLE
分片后涉及数据迁移问题

### ISSUE THREAD

**Issue by david1228** [dangdangdotcom/sharding-jdbc#258]
开源中国社区的提过的问题：https://www.oschina.net/question/107665_2242887

这里我想还要继续问下。
一个视频A分片可能是不固定的，可能关联到某一个专辑上，也可能跟专辑解除关联。
这种场景下，我在做数据迁移的时候，如何来做这个分片算法的实现呢？

**Comment by terrymanu** [comment]
分片算法只是用于确定如何路由到正确额数据，因此如果分片键改了而数据还在旧表里，就永远无法被路由到了。
因为sharding-jdbc不负责数据迁移，因此这块给不了你什么建议了。
