### ISSUE TITLE
1.4.2 proxool 链接池有bug

### ISSUE THREAD

**Issue by letian313** [dangdangdotcom/sharding-jdbc#259]
测试场景：
版本 1.4.2
链接池 proxool 
环境    spring3.2+hibernate4.2
结果  分库无效；
连接池改用druid 则数据可以正常分库

在版本1.3.3测试proxool正常

相关日志
DEBUG c.d.d.r.s.router.SQLRouteEngine - master:INSERT INTO ccp_sms_req (id, accountId, num) VALUES (replace(uuid(), '-', ''), ?, ?) [1000, 11120007310]
DEBUG c.d.d.r.s.router.SQLRouteEngine - 11001:INSERT INTO ccp_sms_req (id, accountId, num) VALUES (replace(uuid(), '-', ''), ?, ?) [1001, 11120007311]
DEBUG c.d.d.r.s.router.SQLRouteEngine - master:INSERT INTO ccp_sms_req (id, accountId, num) VALUES (replace(uuid(), '-', ''), ?, ?) [1002, 11120007312]

测试结果 在 proxool 连接池下的实际结果为 3条数据都插入到了master库；改用druid 连接池则复合预期；
期望结果 2条数据入到master库，1条数据入到11001库；

**Comment by terrymanu** [comment]
从原理上说，sharding jdbc和连接池没关系的。因此这个问题能否请您定位下具体的原因，或换其他连接池试试

**Comment by letian313** [comment]
我后续再跟进下看哪个地方出的问题，从当前的测试结果上看，用druid 和 proxool 在1.3.3版本是都没问题的，proxool 在1.4.2版本上测试出的问题

**Comment by haocao** [comment]
请提供分库策略及proxool的版本，最好提供一个完整的Example工程，方便定位问题，谢谢。

**Comment by haocao** [comment]
使用Proxool配置多个数据源时，应该为每个数据源设置alias，因为Proxool在使用连接时会判断连接池中是否包含已存在的alias，不配置alias会造成每次获取都只从一个数据源中获取连接。
```java
    if(!ConnectionPoolManager.getInstance().isPoolExists(this.alias)) {
        this.registerPool();
    }
```

**Comment by haocao** [comment]
详情可参见FAQ：http://dangdangdotcom.github.io/sharding-jdbc/01-start/faq/
