### ISSUE TITLE
咨询两个问题，批量插入和SpringBoot!

### ISSUE THREAD

**Issue by hualunqun** [dangdangdotcom/sharding-jdbc#260]
#### 2、怎么跟SpringBoot进行结合使用，有没有相关的使用案例。

>如上，谢谢。

**Comment by terrymanu** [comment]
批量插入不支持，请参见：http://dangdangdotcom.github.io/sharding-jdbc/01-start/limitations/

**Comment by terrymanu** [comment]
springboot结合使用就是自己创建bean，相关的例子，google和github上有很多，可以自行搜索
