### ISSUE TITLE
目前版本在使用Long作为分表键值时候，between条件初始化报错

### ISSUE THREAD

**Issue by yangchangyong0** [dangdangdotcom/sharding-jdbc#268]
XML配置：

   <rdb:strategy id="tableShardingStrategy" sharding-columns="index_no"
                  algorithm-class="com.ycy.sharding.SingleKeyModuloTableShardingAlgorithm"  />
    <rdb:data-source id="dataSource">
        <rdb:sharding-rule data-sources="dataSource" default-data-source="dataSource"
                          >
            <rdb:table-rules>
                <rdb:table-rule logic-table="tb_user"
                                actual-tables="tb_user_${1..10}"
                                table-strategy="tableShardingStrategy"   >
                </rdb:table-rule>
            </rdb:table-rules>
        </rdb:sharding-rule>
    </rdb:data-source>

JAVA初始化分表方法：
public class SingleKeyModuloTableShardingAlgorithm implements SingleKeyTableShardingAlgorithm<Long> {

    @Override
    public String doEqualSharding(final Collection<String> availableTargetNames, final ShardingValue<Long> shardingValue) {
      return null;
    }

    @Override
    public Collection<String> doInSharding(final Collection<String> availableTargetNames, final ShardingValue<Long> shardingValue) {
        return null;
    }

    @Override
    public Collection<String> doBetweenSharding(final Collection<String> availableTargetNames, final ShardingValue<Long> shardingValue) {
        Collection<String> result = new LinkedHashSet<>(availableTargetNames.size());
        Range<Long> range = shardingValue.getValueRange();
        for (Long value = range.lowerEndpoint(); value <= range.upperEndpoint(); value++) {
            for (String each : availableTargetNames) {
                if (each.endsWith(value % 10 + "")) {
                    result.add(each);
                }
            }
        }
        return result;
    }
}

**Comment by haocao** [comment]
请提供详细的出错信息及SQL。

**Comment by terrymanu** [comment]
无法重现，并且长时间无反馈。
请参见sharding-jdbc-example
