### ISSUE TITLE
请问作者，是否支持单表同一个库分片

### ISSUE THREAD

**Issue by YcJu** [dangdangdotcom/sharding-jdbc#269]
即有一张表，我想通过sharding-jdbc 在插入这张逻辑表时，自动通过某个规则，分片到不同的表，当SQL执行，路由根据分片规则决定将此条数据落在具体的某张实体表中，这些表都在同一个数据库中

**Comment by terrymanu** [comment]
支持，分库+分表，仅分库，仅分表即为sharding-JDBC的基本功能。

**Comment by terrymanu** [comment]
example中有相应的示例
