### ISSUE TITLE
能否支持部分SQL的“透传”？

### ISSUE THREAD

**Issue by tistyzc** [dangdangdotcom/sharding-jdbc#270]
比如数据库中只有部分表要分库或分表，其它全部定向到默认数据库，那针对定向到默认数据库的那些操作，能否直接透传至下层数据库，这样就可以支持包括子查询、union、limit等一些不好处理的，对系统来说，就是可以分步实施数据库的迁移。

**Comment by terrymanu** [comment]
暂时不打算支持这个功能。我们希望sharding-jdbc在任何状态下都保持对外反馈的一致性，而不是在未分库分表“隐藏”，在配置分库分表时才暴露一些SQL不支持。
这样对于用户来说使用成本较高，很可能导致用户研究什么样的配置支持什么SQL。
不参与分库分表的数据库建议不使用Sharding-JDBC，而是用标准的DataSource与Sharding-JDBC配合使用。
Sharding-JDBC的定位是分库分表水平扩展方案，而非垂直+水平扩展方案。

**Comment by limingwei** [comment]
其实我也觉得这个想法，是个好东西，有用的，有需要的

**Comment by limingwei** [comment]
看来不是我一个人这样想

**Comment by limingwei** [comment]
或者可以把这个功能做成一个开关，默认关闭呗

**Comment by limingwei** [comment]
这个如果做了，就是提升产品易用性，降低门槛啊
