### ISSUE TITLE
分页的bug

### ISSUE THREAD

**Issue by dale19900108** [dangdangdotcom/sharding-jdbc#272]
数据分布不均匀的，第一个数据库表中有该用户数据，第二个数据库中，表中没有用户数据，根据用户编号查询，按照创建时间排序进行分页查询请求，前几页返回的数据正确，超过了最大页数的分页，返回的数据不是空。并且一直有数据。
举例A表中有该用户的数据100条，B表中没有该用户数据
分页大小每次10条，则，请求13页的时候，仍然会得到数据。
### Which version of Sharding-Jdbc do you using?
1.4.2
### Actual behavior
有数据返回，看样子像是第一页的数据

**Comment by terrymanu** [comment]
duplicate with #239

**Comment by dale19900108** [comment]
duplicate with #239
但是貌似1.5.0还没解决 ？

**Comment by terrymanu** [comment]
fixed at 1.5.0.M2
