### ISSUE TITLE
SquirrelSQL integration

### ISSUE THREAD

**Issue by fbarbat** [dangdangdotcom/sharding-jdbc#273]
Hi, I've just saw your project and looks great. Thanks for open sourcing it! 

I would really like to use SquirrelSQL to query sharded databases with sharding-jdbc. I am just a beginner in sharding-jdbc and SquirrelSQL API but from what I understand, it wouldn't be too difficult to integrate them. For example, it looks like a jdbc Driver wrapping sharding-jdbc could be implemented harnessing Yaml support. This way, a Squirrel user would only have to drop sharding-jdbc jar in lib directory, all its dependencies :(, and a Yaml configuration file, and that would be it. We would have to make sure there is no classpath conflict though. Configuration through UI could be implemented later.

What are your thoughts about this? Did you have any ideas about it? 

Maybe I can start testing these ideas in some days. Any advice would be appreciated. Thanks!

**Comment by terrymanu** [comment]
it is a good idea. If you want use SquirrelSQL also use jdbc to access database, so I think you just need develop a new ui for config sharding rule. But sharding-jdbc only support CRUD SQL, cannot support CREATE, DROP etc.

**Comment by terrymanu** [comment]
no response any more, close now. If you want discuss it, please reopen it.
