### ISSUE TITLE
请问Sharding-Jdbc可以根据策略自动建表吗？

### ISSUE THREAD

**Issue by komawei** [dangdangdotcom/sharding-jdbc#275]
您好！
我想请教一下：
例如我有一个操作日志表t_log，分表策略是按照操作用户的userId去划分，原来只有A\B两个用户，对应t_log_a和t_log_b，那么当我插入一条用户为C的操作日志，Sharding-Jdbc会动态创建t_log_c表，并且插入这条插入日志吗

**Comment by terrymanu** [comment]
不可以
