### ISSUE TITLE
未命中key进行分散查询的连接池拒绝问题

### ISSUE THREAD

**Issue by lulonglong** [dangdangdotcom/sharding-jdbc#278]
如果在业务场景中存在不按照shardingkey查询的场景，会很容易造成java.util.concurrent.RejectedExecutionException错误

这种查询虽然数量相对较少，但是也会小概率的存在同时几个请求一起来。
正是这种小概率也不值得开发者再去做数据冗余来避免这种情况。

目前源代码：new ThreadPoolExecutor(executorMinIdleSize, executorMaxSize,
executorMaxIdleTimeoutMilliseconds, TimeUnit.MILLISECONDS,
new SynchronousQueue()))
源代码中使用了SynchronousQueue，希望能提供给开发者配置缓冲队列的选择

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
所有版本

### Expected behavior
希望能提供给开发者配置缓冲数量的选择。

### Actual behavior
如果在业务场景中存在不按照shardingkey查询的场景，会很容易造成java.util.concurrent.RejectedExecutionException错误

### Steps to reproduce the behavior
分表40张，不按照shardingkey同时三四个查询请求

**Comment by terrymanu** [comment]
这个值可以配置。参考文档：http://dangdangdotcom.github.io/sharding-jdbc/02-guide/configuration/ 搜索executor.max.size即可

**Comment by lulonglong** [comment]
这个配置大了还是会偶尔出错，解决不了根本问题。增加可配置的缓存队列是一个可选方案

**Comment by terrymanu** [comment]
Sharding-JDBC定位为JDBC驱动增强，轻量级是最基本守则。因此不会增加第三方缓存来增加Sharding-JDBC的复杂度。

如果线程队列已经溢出，证明该服务器已经超过可承受的极值，如果Sharding-JDBC不用线程池保护性拒绝请求，则应用即会被冲垮。

因此这种情况服务器应考虑扩容
