### ISSUE TITLE
nextval函数不支持

### ISSUE THREAD

**Issue by amikehero** [dangdangdotcom/sharding-jdbc#282]
Please answer these questions before submitting your issue. Thanks!

### 使用sharding-jdbc 1.5.0.M1

执行如下nextval函数，无法解析：
select nextval('sequenceId')

由于系统是分布式，是否需要采用其他方式生产全局唯一ID。

执行中报如下错误：
 Error querying database.  Cause: com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: Cannot find table rule and default data source with logic tables: '[]'
The error may exist in file [/home/gzUp/tomcat-dev-1/webapps/notify-system-webapp/WEB-INF/classes/mappers/SequenceMapper.xml]
The error may involve SequenceDao.getSequence-Inline
The error occurred while setting parameters
SQL: select   nextval(?)
Cause: com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: Cannot find table rule and default data source with logic tables: '[]'

**Comment by terrymanu** [comment]
不支持特殊语法
