### ISSUE TITLE
配置读写分离时,查询没有配置策略的表会报错bug

### ISSUE THREAD

**Issue by jianbinJava** [dangdangdotcom/sharding-jdbc#283]
1.5.0.M2 最新版本,
我在配置读写分离时如果查询没有配置分表策略的表会报找不到分表策略异常
Cannot find table rule and default data source with logic tables: '%s'", logicTables
也就是说业务里所有的表都要配置策略,否则执行不了,

**Comment by terrymanu** [comment]
配置default-data-source能解决你的问题么

**Comment by jianbinJava** [comment]
还是解决不了,应该不是default-datasource 的问题,是找不到指定表的分表策略的问题..
我目前只做读写分离,未对任何表做分表策略..

**Comment by terrymanu** [comment]
这部分会在1.6.0增强。1.6.0主要是要对配置进行调整。现在的1.5.x及其以前版本不支持仅读写分离。
因此这个issue我先关了，敬请期待1.6.0
