### ISSUE TITLE
动态表配置，联表查询时分页查询第三页时会将第一页，第二页数据也返回。

### ISSUE THREAD

**Issue by michaelzhou2016** [dangdangdotcom/sharding-jdbc#285]
Please answer these questions before submitting your issue. Thanks!

### Expected behavior

查询第三页时，只返回第三页数据

### Actual behavior

查询第三页时会将第一页，第二页数据也返回。

### Steps to reproduce the behavior

两个动态表联表查询，使用分页插件pageHelper

### Please provide the reproduce example codes (such as github link) if possible.
sharding-jdbc 配置：

private Map<String, TableRuleConfig> createTableRuleConfigMap() {
        Map<String, TableRuleConfig> result = new HashMap<>(3);
        result.put("ord_order_info", createDynamicTableRuleConfig("ord_order_info"));
        result.put("ord_order_detail", createDynamicTableRuleConfig("ord_order_detail"));
        result.put("pay_flow", createDynamicTableRuleConfig("pay_flow"));
        return result;
    }

    private StrategyConfig getTableStrategyConfigForExpression(String tableName) {
        StrategyConfig result = new StrategyConfig();
        result.setShardingColumns("store_id");
        result.setAlgorithmExpression(tableName + "_${store_id}");
        return result;
    }

    private TableRuleConfig createDynamicTableRuleConfig(String tableName) {
        TableRuleConfig result = new TableRuleConfig();
        result.setDynamic(true);
        result.setDataSourceNames("db_order_sharding");
        result.setTableStrategy(getTableStrategyConfigForExpression(tableName));
        return result;
    }

SQL：
select ooi.id as orderCode, ooi.store_Id as storeID,
         ooi.payment_type_id as paymentTypeId, ooi.order_total as orderAmount,
         ooi.create_time as saleDate, ooi.payment_time as paymentDate,
         ooi.member_cardNo as customerCode, ooi.user_tel as customerPhone,
         ooi.order_node as remark,
         ood.product_sku, ood.product_barcode, ood.product_name,
         ood.product_format, ood.product_unit, ood.number
        from ord_order_info ooi, ord_order_detail ood
        where ooi.id = ood.order_id
        <if test="orderId!=null and orderId!=''">
            and ooi.id = #{orderId}
        </if>
        and ooi.store_id = #{storeId}
        and ood.store_id = #{storeId}

**Comment by terrymanu** [comment]
我们并未将分页插件pageHelper列入兼容列表，因此不会对此issue进行支持。

如果您想继续对此issue追踪，请提供如下信息：
1. Sharding-JDBC版本号
2. 被pageHelper修改以后的SQL
3. Sharding-JDBC的info执行日志

或提供可重现的全部代码也可

**Comment by terrymanu** [comment]
经测试这应该是1.5.0.M2的bug，已于1.5.0.M3中修复。
