### ISSUE TITLE
不进行分表的表中含有or条件，应该支持去默认的数据源

### ISSUE THREAD

**Issue by amikehero** [dangdangdotcom/sharding-jdbc#288]
### Which version of Sharding-Jdbc do you using?

1.5.0.M1

### Expected behavior

对于不进行分表的表中含有or条件，应该需要支持去默认数据源。否则使用sharding-jdbc后，对于不进行分表的表会出现很多 不必要的限制。
请问，不这样实现是因为解析有困难还是有其他原因。

### Actual behavior

报错，不支持OR条件。

Error querying database. Cause: com.dangdang.ddframe.rdb.sharding.parsing.parser.exception.SQLParsingUnsupportedException: Not supported token 'OR'.

The error may exist in file [/home/gzUp/tomcat-dev-1/webapps/notify-system-webapp/WEB-INF/classes/mappers/DBrefusedetailMapper.xml]

The error may involve DBrefusedetailMapper.selectCountByParam-Inline

The error occurred while setting parameters

SQL: select count(*) as totalCount, sum(CONVERT(trans_amount,DECIMAL)) as totalAcc from t_sysnotice_refusedetail where 1=1 and trans_init_time >= ? and trans_init_time <= ? and trans_type in ( ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? ) and (cust_id = ? or expander_cust_id = ? or acquirer_cust_id = ? or operator_cust_id = ? or platform_cust_id = ? )

Cause: com.dangdang.ddframe.rdb.sharding.parsing.parser.exception.SQLParsingUnsupportedException: Not supported token 'OR'.

**Comment by terrymanu** [comment]
sharding-jdbc的设计理念是简洁清晰。
不想让使用者使用时区猜测什么条件下支持什么东西，这样排列组合太多，太过复杂。
这不符合sharding-jdbc的设计初衷。
因此or在任何条件下都不支持，请理解

**Comment by limingwei** [comment]
看看  看看
有这种想法的人  真的很多
也许这部分人，比如我，技术水平不够，思想不够先进
但，的确有不少比例的人是这样想的啊
