### ISSUE TITLE
HintManagerHolder.clear() when DataSourceUtils.releaseConnection

### ISSUE THREAD

**Issue by lemonzone2010** [dangdangdotcom/sharding-jdbc#293]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
```xml
            <groupId>com.dangdang</groupId>
            <artifactId>sharding-jdbc-core</artifactId>
        <version>1.4.1</version>
```
### Expected behavior
1. select sql executed on master DB
2. HintManagerHolder.isMasterRouteOnly(): true
### Actual behavior
1. select sql executed on slave DB
2. HintManagerHolder.isMasterRouteOnly(): false

### Steps to reproduce the behavior
1.  HintManager.getInstance().setMasterRouteOnly();
2.  jdbcTemplate.query("select * from table where id=123",new XXXRowMapper());
3. jdbcTemplate.execute()   method content 
```java
	try {
		}
		catch (SQLException ex) {
		finally {
	//The following code will execute ShardingConnection.close()  and  HintManagerHolder.clear();
			DataSourceUtils.releaseConnection(con, getDataSource());
		}
```
4. The next query sql will use the slave DB
```java
jdbcTemplate.query("select * from table where id=1111",new XXXRowMapper());   
```
### Please provide the reproduce example codes (such as github link) if possible.
nothing

**Comment by terrymanu** [comment]
HintManager and Connection is not same lifecycle. If want release HintManager, just call HintManager.close(), or use try with resources, put HintManager and Connection in same try block
