### ISSUE TITLE
Sharding-Jdbc现在是否支持一个库中的部分表配置分表策略？

### ISSUE THREAD

**Issue by komawei** [dangdangdotcom/sharding-jdbc#294]
版本：1.5.0.M3

现在在一个项目中，只为订单表PU_Order配置了table rule，在启动的时候报错：
Cannot find table rule and default data source with logic tables: '[BD_Dictionary, BD_DictionaryType, OPM_User]'

这几个表与订单表没有关系，只是启动的时候读取这几个表的数据。

spring配置如下：
<rdb:data-source id="shardingDataSource">
        <rdb:sharding-rule data-sources="dataSource" default-data-source="dataSource">
            <rdb:table-rules>
                <rdb:table-rule logic-table="PU_Order" actual-tables="PU_Order_${0..19}" table-strategy="purchaseOrderTableStrategy" />
            </rdb:table-rules>
            <rdb:binding-table-rules>
                <rdb:binding-table-rule logic-tables="PU_Order"/>
            </rdb:binding-table-rules>
            <rdb:default-database-strategy sharding-columns="none" 
            	algorithm-class="com.dangdang.ddframe.rdb.sharding.api.strategy.database.NoneDatabaseShardingAlgorithm"/>
            <rdb:default-table-strategy sharding-columns="none" 
            	algorithm-class="com.dangdang.ddframe.rdb.sharding.api.strategy.table.NoneTableShardingAlgorithm"/>
        </rdb:sharding-rule>
        <rdb:props>
            <prop key="metrics.enable">true</prop>
        </rdb:props>
    </rdb:data-source>

**Comment by komawei** [comment]
我给[BD_Dictionary 配上了分表策略之后，报错消失。
意思是rdb:default-table-strategy  没有生效？

**Comment by terrymanu** [comment]
目前不支持，所有的sql中的表都需要配置，不然无法找到数据源。如果不配置的表会从默认数据源找，可以配置上默认数据源

**Comment by komawei** [comment]
默认数据源我也配上了：<rdb:sharding-rule data-sources="dataSource" default-data-source="dataSource">
不过还是报这个错

**Comment by terrymanu** [comment]
是不是因为你的表不在默认数据源里

**Comment by komawei** [comment]
也在的，现在是我每个表都配上了不需要分表的策略，才不报错了

**Comment by dexvo** [comment]
请教一下对于同一个数据源中的不同的表可以配置不同的table strategy吗？
