### ISSUE TITLE
查询字段为浮点数科学计数法的解析

### ISSUE THREAD

**Issue by YunaiV** [dangdangdotcom/sharding-jdbc#296]
### Which version of Sharding-Jdbc do you using?

1.5.0.M4-SNAPSHOT

### Steps to reproduce the behavior

SQL 如下：

```SQL
SELECT 1.321312FE100 
```

MySQL 客户端执行结果为：

```
mysql> SELECT 1.321312FE100
    -> ;
+----------+
| FE100    |
+----------+
| 1.321312 |
+----------+
```

sjdbc 解析结果为

```
SELECT	SELECT
1.321312F	FLOAT
E100	IDENTIFIER
;	SEMI
	END
```

`1.321312FE100` 被拆成了两个 Token

😈实际这么去 SQL 应该不多。

**Comment by terrymanu** [comment]
经实际测试发现，

``` sql
SELECT 1.321312FE100
```

MySQL会将其解析为SELECT 1.321312(数字) FE100(别名)。因此现在的做法是正确的。
但这里确实有一个bug，lexer会将其解析为SELECT 1.321312F(数字) E100(别名)，因为结尾的F，lexer会认为是浮点数的结束符。
但这种情况非常少见，也非标准用法，因此就不改了。
