### ISSUE TITLE
你们的parent pom没有提交到maven仓库。

### ISSUE THREAD

**Issue by cnhans** [dangdangdotcom/sharding-jdbc#3]
<groupId>com.dangdang</groupId>
<artifactId>sharding-jdbc</artifactId>
<version>1.0.0</version>

**Comment by cnhans** [comment]
试用难使用，代码使用了太多第三方，转用mycat！

**Comment by terrymanu** [comment]
感谢花费宝贵时间试用。请问难使用在哪里，代码使用了哪些第三发导致您难于使用。您的建议有助于我们改善。谢谢

**Comment by terrymanu** [comment]
parent pom一般不会直接部署，参见springframework

**Comment by haocao** [comment]
parent pom已提交到maven仓库。
