### ISSUE TITLE
类型转换错误

### ISSUE THREAD

**Issue by lanmo** [dangdangdotcom/sharding-jdbc#300]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
sharding-jdbc-core-1.4.2
### Steps to reproduce the behavior
![image](https://user-images.githubusercontent.com/7801191/28616511-955ef504-722f-11e7-9b9b-4b668c3ab9da.png)
![image](https://user-images.githubusercontent.com/7801191/28616526-a5297252-722f-11e7-95d8-21690ec16c33.png)
写的long，取值的时候是int，这样会报类型转换错误

**Comment by terrymanu** [comment]
请问用的是否是inline表达式

**Comment by terrymanu** [comment]
能否升级至1.5.0.M3再试一下，精力有限，之前的版本不在维护

**Comment by lanmo** [comment]
升级到1.5.0.M3 问题已解决，也就是以前的版本会存在这个问题是吗？

**Comment by terrymanu** [comment]
应该是吧，既然你测出来了。
不过既然新版本已解决，欢迎使用新版本
