### ISSUE TITLE
根据IP生成workerId的思路

### ISSUE THREAD

**Issue by DogFc** [dangdangdotcom/sharding-jdbc#301]
在分析了IPIdGenerator生成workerId的思路后，感觉对服务器IP后10位（特别是IPV6）数值比较约束。
因为workerId最大限制是2^10，我们生成的workerId只要满足小于最大workerId即可。
因此有以下的优化点，很大程度上可保证不受服务器IP规范限制，都可直接根据IP生成workerId。

1. 针对IPV4:
       IP最大 255.255.255.255。而（255+255+255+255) < 1024。
       因此采用IP段数值相加即可生成唯一的workerId，不受IP位限制。

2. 针对IPV6:
       IP最大ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
       为了保证相加生成出的workerId < 1024,思路是将每个bit位的后6位相加。这样在一定程度上也优化了workerId不重复的问题。

详细代码：
      https://github.com/DogFc/sharding-jdbc/commit/f5d40257ed5f00e24f7160139978eac3986b1a73

**Comment by DogFc** [comment]
发现一个我思路上的问题，相加IP段的方法，最多也只能满足1024台worker，和用IP后10位生成worker的数量是相同的。
因此我的方法并没有更高程度的优化，反而在运维分配机器IP的时候，控制IP后十位不同比控制整个IP段相加不同更直观一点。
^-^...

**Comment by terrymanu** [comment]
欢迎直接pr。另外请注意下，pr请提在当前开发的分支，而非master，多谢

**Comment by terrymanu** [comment]
merged at 1.5.0.m4
