### ISSUE TITLE
升级版本1.5.0.M3以后，连表查询的所有表都必须要配置上tableRule么？ 另外那个bindingTableRule是个什么用途 ？

### ISSUE THREAD

**Issue by ijiaojian** [dangdangdotcom/sharding-jdbc#304]
1.5.0M3

private RoutingResult route(final List<Object> parameters, final SQLStatement sqlStatement) {
        Collection<String> tableNames = sqlStatement.getTables().getTableNames();
        RoutingEngine routingEngine;
        if (1 == tableNames.size() || shardingRule.isAllBindingTables(tableNames)) {
            routingEngine = new SimpleRoutingEngine(shardingRule, parameters, tableNames.iterator().next(), sqlStatement);
        } else {
            // TODO 可配置是否执行笛卡尔积
            routingEngine = new ComplexRoutingEngine(shardingRule, parameters, tableNames, sqlStatement);
        }
        return routingEngine.route();
    }

这是选择路由引起的一段代码，如果查询的表的张数等于1，或者查询的表都是bindingTable 才使用SimpleRoutingEngine ，否则使用ComplexRoutingEngine。 关键是使用ComplexRoutingEngine时，我查询的两个表没有配置TableRule，（理论上不需要分表的就可以不配置分表规则）， 结果在ComplexRoutingEngine里面就报错。throw new ShardingJdbcException("Cannot find table rule and default data source with logic tables: '%s'", logicTables);

想了解下，现在这个是这样设计的么?  必须给每张表配置分表规则 ？

**Comment by terrymanu** [comment]
1. 是的。被sharding-jdbc管理的数据源对任何表都是一致对待，无论是否分，都需要配。
2. 请阅读文档，BindingTable部分。

**Comment by ijiaojian** [comment]
@terrymanu   不需要分表的表也需要配置TableRule，请问这个设计是出于什么考虑呢 ？ 因为在1.5.0之前的版本是不需要配置TableRule的

**Comment by terrymanu** [comment]
都是必须配的，1.4也一样，除非用了default-datasource。不过1.4不太严谨，可能某些情况下不配也不报错，但是行为却不一定对。1.5做了完整性校验。

**Comment by ijiaojian** [comment]
@terrymanu   看到开源中国帖子里面你们写的1.5.0.M3版本会支持or查询， 目前我使用的1.5.0.M3版本 ，似乎还是不支持or查询呢

SQLParser.java

 private void parseConditions(final SQLStatement sqlStatement) {
        do {
            parseComparisonCondition(sqlStatement);
        } while (skipIfEqual(DefaultKeyword.AND));
        if (equalAny(DefaultKeyword.OR)) {
            throw new SQLParsingUnsupportedException(getLexer().getCurrentToken().getType());
        }
    }

**Comment by terrymanu** [comment]
先不支持了，比较难做。以后有机会再支持
