### ISSUE TITLE
spring data jpa无法分页

### ISSUE THREAD

**Issue by iswu2013** [dangdangdotcom/sharding-jdbc#305]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.4.2
### Expected behavior
分页功能
### Actual behavior
无法分页
### Steps to reproduce the behavior
我用的spring data
### Please provide the reproduce example codes (such as github link) if possible.
@Override
	public PageImplE<T> page(final D vo) {
		Page<T> page = baseRepository.findAll(new Specification<T>() {

			@Override
			public Predicate toPredicate(Root<T> root, CriteriaQuery<?> query, CriteriaBuilder cb) {
				List<Predicate> list = new ArrayList<>();
				list.add(cb.equal(root.<String>get("entityState"), EntityState.N.name()));

				Field[] fields = vo.getClass().getDeclaredFields();

				for (Field field : fields) {
					if(IgnoreField.hasField(field.getName())) {
						continue;
					}
					String fileName = field.getName();

					// 生成String类型参数
					this.genString(vo, root, cb, list, field, fileName);

					// 生成int or long类型
					this.genIntOrLong(vo, root, cb, list, field, fileName);

					// 生成list类型
					this.genList(vo, root, cb, list, field, fileName);

					// 生成Date类型
					this.genDate(vo, root, cb, list, field, fileName);

					// 生成Boolean
					this.genBoolean(vo, root, cb, list, field, fileName);
				}

				Predicate[] p = new Predicate[list.size()];
				return cb.and(list.toArray(p));
			}

			/**
			 * 生成in
			 * 
			 * @param vo
			 * @param root
			 * @param cb
			 * @param list
			 * @param field
			 * @param fileName
			 */
			private void genList(D vo, Root<T> root, CriteriaBuilder cb, List<Predicate> list, Field field,
					String fileName) {
				if (field.getGenericType().toString().equals(QueryGenericType.List.getGenericType())) {
					try {
						String fieldValueStr = BeanUtils.getIndexedProperty(vo, fileName);

						List<Long> fieldValue = new ArrayList<>();
						if (fieldValue != null && fieldValue.size() > 0) {
							if (fileName.substring(0, fileName.indexOf(Constants.QUESTION_GAP))
									.equals(QueryType.in.name())) {
								list.add(cb.in(root.get("id")).value(fieldValue));
							}
						}
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
			}

			/**
			 * 生成日期
			 * 
			 * @param vo
			 * @param root
			 * @param cb
			 * @param list
			 * @param field
			 * @param fileName
			 */
			private void genDate(D vo, Root<T> root, CriteriaBuilder cb, List<Predicate> list, Field field,
					String fileName) {
				if (field.getGenericType().toString().equals(QueryGenericType.Date.getGenericType())) {
					try {
						if(!fileName.contains(Constants.QUESTION_GAP)) {
							return;
						}
						String subFieldName = fileName.substring(fileName.indexOf(Constants.QUESTION_GAP)+1);
						
						if (fileName.substring(0, fileName.indexOf(Constants.QUESTION_GAP))
								.equals(QueryType.between.name())) {
							if (!fileName.endsWith(Constants.BETWEEN_END)) {
								Date start = DateUtils.parseDate(BeanUtils.getProperty(vo, fileName),
										"yyyy-MM-dd HH:mm:ss");
								Date end = DateUtils.parseDate(
										BeanUtils.getProperty(vo, fileName + Constants.BETWEEN_END),
										"yyyy-MM-dd HH:mm:ss");

								list.add(cb.between(root.<Date>get(subFieldName), start, end));
							}
						}
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
			}

			/**
			 * 
			 * @param vo
			 * @param root
			 * @param cb
			 * @param list
			 * @param field
			 * @param fileName
			 */
			private void genBoolean(D vo, Root<T> root, CriteriaBuilder cb, List<Predicate> list, Field field,
					String fileName) {
				if (field.getGenericType().toString().equals(QueryGenericType.Boolean.getGenericType())) {
					try {
						String fieldValueStr = BeanUtils.getProperty(vo, fileName);
						boolean fieldValue = Boolean.parseBoolean(fieldValueStr);
						
						if(!fileName.contains(Constants.QUESTION_GAP)) {
							return;
						}
						String subFieldName = fileName.substring(fileName.indexOf(Constants.QUESTION_GAP)+1);

						if (fileName.substring(0, fileName.indexOf(Constants.QUESTION_GAP))
								.equals(QueryType.equal.name())) {
							list.add(cb.equal(root.<Boolean>get(subFieldName), fieldValue));
						}

						if (fileName.substring(0, fileName.indexOf(Constants.QUESTION_GAP))
								.equals(QueryType.notEqual.name())) {
							list.add(cb.notEqual(root.<Boolean>get(subFieldName), fieldValue));
						}
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
			}

			/**
			 * 生成
			 * 
			 * @param vo
			 * @param root
			 * @param cb
			 * @param list
			 * @param field
			 * @param fileName
			 */
			private void genIntOrLong(final D vo, Root<T> root, CriteriaBuilder cb, List<Predicate> list,
					Field field, String fileName) {
				if(!fileName.contains(Constants.QUESTION_GAP)) {
					return;
				}
				String subFieldName = fileName.substring(fileName.indexOf(Constants.QUESTION_GAP)+1);
				
				if (field.getGenericType().toString().equals(QueryGenericType.Int.getGenericType())
						|| field.getGenericType().toString().equals(QueryGenericType.Long.getGenericType())) {
					try {
						boolean isInteger = field.getGenericType().toString()
								.equals(QueryGenericType.Int.getGenericType());
						String fieldValueStr = BeanUtils.getProperty(vo, fileName);
						if (!StringUtils.isEmpty(fieldValueStr)) {
							if (isInteger) {
								int fieldValue = Integer.parseInt(fieldValueStr);
								if(fieldValue <= 0) {
									return;
								}
								if (fileName.substring(0, fileName.indexOf(Constants.QUESTION_GAP))
										.equals(QueryType.equal.name())) {
									list.add(cb.equal(root.<Integer>get(subFieldName), fieldValue));
								}

								if (fileName.substring(0, fileName.indexOf(Constants.QUESTION_GAP))
										.equals(QueryType.notEqual.name())) {
									list.add(cb.notEqual(root.<Integer>get(subFieldName), fieldValue));
								}

								if (fileName.substring(0, fileName.indexOf(Constants.QUESTION_GAP))
										.equals(QueryType.between.name())) {
									if (!fileName.endsWith(Constants.BETWEEN_END)) {
										int start = Integer.parseInt(BeanUtils.getProperty(vo, fileName));
										int end = Integer
												.parseInt(BeanUtils.getProperty(vo, fileName + Constants.BETWEEN_END));
										list.add(cb.between(root.<Integer>get(subFieldName), start, end));
									}
								}

								if (fileName.substring(0, fileName.indexOf(Constants.QUESTION_GAP))
										.equals(QueryType.greaterThan.name())) {
									list.add(cb.greaterThan(root.<Integer>get(subFieldName), fieldValue));
								}

								if (fileName.substring(0, fileName.indexOf(Constants.QUESTION_GAP))
										.equals(QueryType.greaterThanOrEqualTo.name())) {
									list.add(cb.greaterThanOrEqualTo(root.<Integer>get(subFieldName), fieldValue));
								}

								if (fileName.substring(0, fileName.indexOf(Constants.QUESTION_GAP))
										.equals(QueryType.lessThan.name())) {
									list.add(cb.lessThan(root.<Integer>get(subFieldName), fieldValue));
								}

								if (fileName.substring(0, fileName.indexOf(Constants.QUESTION_GAP))
										.equals(QueryType.lessThanOrEqualTo.name())) {
									list.add(cb.lessThanOrEqualTo(root.<Integer>get(subFieldName), fieldValue));
								}
							} else {
								long fieldValue = Long.parseLong(fieldValueStr);
								if(fieldValue <= 0) {
									return;
								}
								if (fileName.substring(0, fileName.indexOf(Constants.QUESTION_GAP))
										.equals(QueryType.equal.name())) {
									list.add(cb.equal(root.<Long>get(subFieldName), fieldValue));
								}

								if (fileName.substring(0, fileName.indexOf(Constants.QUESTION_GAP))
										.equals(QueryType.notEqual.name())) {
									list.add(cb.notEqual(root.<Long>get(subFieldName), fieldValue));
								}

								if (fileName.substring(0, fileName.indexOf(Constants.QUESTION_GAP))
										.equals(QueryType.between.name())) {
									if (!fileName.endsWith(Constants.BETWEEN_END)) {
										long start = Long.parseLong(BeanUtils.getProperty(vo, fileName));
										long end = Long
												.parseLong(BeanUtils.getProperty(vo, fileName + Constants.BETWEEN_END));
										list.add(cb.between(root.<Long>get(subFieldName), start, end));
									}
								}

								if (fileName.substring(0, fileName.indexOf(Constants.QUESTION_GAP))
										.equals(QueryType.greaterThan.name())) {
									list.add(cb.greaterThan(root.<Long>get(subFieldName), fieldValue));
								}

								if (fileName.substring(0, fileName.indexOf(Constants.QUESTION_GAP))
										.equals(QueryType.greaterThanOrEqualTo.name())) {
									list.add(cb.greaterThanOrEqualTo(root.<Long>get(subFieldName), fieldValue));
								}

								if (fileName.substring(0, fileName.indexOf(Constants.QUESTION_GAP))
										.equals(QueryType.lessThan.name())) {
									list.add(cb.lessThan(root.<Long>get(subFieldName), fieldValue));
								}

								if (fileName.substring(0, fileName.indexOf(Constants.QUESTION_GAP))
										.equals(QueryType.lessThanOrEqualTo.name())) {
									list.add(cb.lessThanOrEqualTo(root.<Long>get(subFieldName), fieldValue));
								}
							}

						}
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
			}

			/**
			 * 生成String类型参数
			 * 
			 * @param vo
			 * @param root
			 * @param cb
			 * @param list
			 * @param field
			 * @param fileName
			 */
			private void genString(final D vo, Root<T> root, CriteriaBuilder cb, List<Predicate> list,
					Field field, String fileName) {
				if (field.getGenericType().toString().equals(QueryGenericType.String.getGenericType())) {
					try {
						String fieldValue = BeanUtils.getProperty(vo, fileName);
						if(!fileName.contains(Constants.QUESTION_GAP)) {
							return;
						}
						String subFieldName = fileName.substring(fileName.indexOf(Constants.QUESTION_GAP)+1);
						if (!StringUtils.isEmpty(fieldValue)) {
							if (fileName.substring(0, fileName.indexOf(Constants.QUESTION_GAP))
									.equals(QueryType.equal.name())) {
					
								list.add(cb.equal(root.<String>get(subFieldName), fieldValue));
							}

							if (fileName.substring(0, fileName.indexOf(Constants.QUESTION_GAP))
									.equals(QueryType.notEqual.name())) {
								list.add(cb.notEqual(root.<String>get(subFieldName), "%" + fieldValue + "%"));
							}

							if (fileName.substring(0, fileName.indexOf(Constants.QUESTION_GAP))
									.equals(QueryType.like.name())) {
								list.add(cb.like(root.<String>get(subFieldName), "%" + fieldValue + "%"));
							}

							if (fileName.substring(0, fileName.indexOf(Constants.QUESTION_GAP))
									.equals(QueryType.notLike.name())) {
								list.add(cb.notLike(root.<String>get(subFieldName), "%" + fieldValue + "%"));
							}
						}
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
			}
		}, vo);

		PageImplE<T> pageImplE = new PageImplE<>();
		BeanUtilsExtended.copyProperties(pageImplE, page);

		return pageImplE;
	}

**Comment by terrymanu** [comment]
请使用1.5.0.M3试一下吧。应该已经修复了

**Comment by iswu2013** [comment]
这么快，谢谢！这就试试

**Comment by iswu2013** [comment]
DataSourceConfig 应该怎样配置呢？现在数据一次取出来了。下面是我的配置文件
package com.uranus.fans.data.provider.config;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import javax.sql.DataSource;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import com.alibaba.druid.pool.DruidDataSource;
import com.dangdang.ddframe.rdb.sharding.api.ShardingDataSourceFactory;
import com.dangdang.ddframe.rdb.sharding.api.rule.DataSourceRule;
import com.dangdang.ddframe.rdb.sharding.api.rule.ShardingRule;
import com.dangdang.ddframe.rdb.sharding.api.rule.TableRule;
import com.dangdang.ddframe.rdb.sharding.api.strategy.table.TableShardingStrategy;
import com.mysql.jdbc.Driver;

@Configuration
public class DataSourceConfig {
	@Bean
	public DataSource getDataSource() {
		return buildDataSource();
	}

	private DataSource buildDataSource() {
		// 设置分库映射
		Map<String, DataSource> dataSourceMap = new HashMap<>(1);
		// 添加两个数据库ds_0,ds_1到map里
		dataSourceMap.put("uranus_fans", createDataSource("uranus_fans"));
		// 设置默认db为ds_0，也就是为那些没有配置分库分表策略的指定的默认库
		// 如果只有一个库，也就是不需要分库的话，map里只放一个映射就行了，只有一个库时不需要指定默认库，但2个及以上时必须指定默认库，否则那些没有配置策略的表将无法操作数据
		DataSourceRule dataSourceRule = new DataSourceRule(dataSourceMap);

		// 设置分表映射，将t_order_0和t_order_1两个实际的表映射到t_order逻辑表
		// 0和1两个表是真实的表，t_order是个虚拟不存在的表，只是供使用。如查询所有数据就是select * from
		// t_order就能查完0和1表的
		TableRule orderTableRule = TableRule.builder("fans").actualTables(Arrays.asList("fans_0", "fans_1", "fans_2", "fans_3", "fans_4", "fans_5", "fans_6", "fans_7", "fans_8", "fans_9"))
				.dataSourceRule(dataSourceRule).build();

		// 具体分库分表策略，按什么规则来分
		ShardingRule shardingRule = ShardingRule.builder().dataSourceRule(dataSourceRule)
				.tableRules(Arrays.asList(orderTableRule))
				.tableShardingStrategy(new TableShardingStrategy("id", new ModuloTableShardingAlgorithm()))
				.build();

		DataSource dataSource = ShardingDataSourceFactory.createDataSource(shardingRule);

		return dataSource;
	}

	/**
	 * 
	 * @param dataSourceName
	 * @return
	 */
	private static DataSource createDataSource(final String dataSourceName) {
		// 使用druid连接数据库
		DruidDataSource result = new DruidDataSource();
		result.setDriverClassName(Driver.class.getName());
		result.setUrl(String.format("jdbc:mysql://localhost:3306/%s?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8", dataSourceName));
		result.setUsername("root");
		result.setPassword("wujinsong");
		return result;
	}
}

**Comment by terrymanu** [comment]
请参照example吧

**Comment by iswu2013** [comment]
好的，多谢！
