### ISSUE TITLE
inline表达式配置的问题

### ISSUE THREAD

**Issue by dgqypl** [dangdangdotcom/sharding-jdbc#307]
使用的是release v1.5.0版本的sharding-jdbc，在配置inline表达式时，如果配置成如下：
actual-tables="order_${[1,2,3,4,5,6,7,8,9,a,b,c,d,e,f]}"
在工程启动时会报错：
Caused by: groovy.lang.MissingPropertyException: No such property: a for class: Script1

如果配置改成：
actual-tables="order_${['1','2','3','4','5','6','7','8','9','a','b','c','d','e','f']}"则不会报错

请确认一下这里是否要加单引号才行，因为我看官方文档上inline表达式这块的例子，字符串是不用加引号的：
![1](https://user-images.githubusercontent.com/25171658/28866660-32786138-77a6-11e7-87ac-8fc644a7b373.png)

**Comment by terrymanu** [comment]
这里文档写错了，字符串需要加引号，只有分片key作为变量，可以不用加引号。我更新下文档。多谢指出。
