### ISSUE TITLE
数据库自增GeneratedKey的返回无效，已经确认不支持。

### ISSUE THREAD

**Issue by xuminwlt** [dangdangdotcom/sharding-jdbc#308]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5.0
### Expected behavior
mysql自增id在Mybatis中能拿到

@Options(useGeneratedKeys = true, keyProperty = "id" )
    boolean add(User user);

### Actual behavior

配置sjdbc的<rdb:generate-key-column column-name="id"/>意味着只能使用分布式id策略，无法满足现有需求，1.4.2一直可以的。

### Steps to reproduce the behavior

 <insert id="insert" useGeneratedKeys="true" keyProperty="orderId">
        INSERT INTO t_order (
          user_id, status
        )
        VALUES (
        #{userId,jdbcType=INTEGER},
        #{status,jdbcType=VARCHAR}
        )
    </insert>

### Please provide the reproduce example codes (such as github link) if possible.

能够像1.4.2一样支持数据库自增id返回GeneratedKey策略，经过调试发现，GeneratedKey仅在配置分布式自增id才会生效。

**Comment by terrymanu** [comment]
fixed at 1.5.1

**Comment by terrymanu** [comment]
fixed at 1.5.1
