### ISSUE TITLE
It seems not support sql statement contains  " <> " 

### ISSUE THREAD

**Issue by denghc0607** [dangdangdotcom/sharding-jdbc#313]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using? 
1.5.0
### Expected behavior
Support complex sql
### Actual behavior
not contains  " <> "

**Comment by pgxxhh** [comment]
mdzz

**Comment by terrymanu** [comment]
please give a example for sql

**Comment by denghc0607** [comment]
SELECT
	j.ID,
	j. STATUS,
	j.JOB_USER,
	j.TYPE,
	j.JOB_LEVEL,
	j.JOB_CREATETIME,
	j.SHARDTIME,
	j.BEFORE_USER,
	j.EXE_USER,
	r.RELEASEDATE,
	r.INNERCODE,
	r.TITLE,
	r.SECONDTITLE,
	r.MEDIASOURCE
FROM
	table1 j,
	table2 r
WHERE
	j.ID = r.JOB_ID
AND j.JOB_USER IN (
	50063730,
	1,
	1645,
	2,
	3206,
	50032273,
	50020450,
	2066,
	50086076
)
AND j.TYPE <> 1
AND j. STATUS IN (1, 5, 6)
ORDER BY
	SHARDTIME DESC,
	JOB_LEVEL DESC

@terrymanu  like this , thank you !!

**Comment by terrymanu** [comment]
fixed at 1.5.1
