### ISSUE TITLE
Select for update 的sql是否支持。

### ISSUE THREAD

**Issue by dale19900108** [dangdangdotcom/sharding-jdbc#315]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5.0
请问是否支持select for update的sql。在测试中，select for update 并不能锁住记录。

**Comment by terrymanu** [comment]
请将SQL和info日志贴出来

**Comment by terrymanu** [comment]
应该是支持的，由于看不到sql，初步判断是sharding-jdbc对sql本身不支持所致

**Comment by dale19900108** [comment]
了解了，确实是支持select for update ，遇到的问题是在测试读写分离时候产生的。在一个没有事务声明的方法中国，调用了两个方法，第一个是查询，第二个是一个带事务的select for update。
期望是：事务中的方法会走主库，实际上。select for update却落到从库。

**Comment by enjoy-live** [comment]
@dale19900108 Hi~ 我确实遇到了和你一样的问题. 请问你怎么解决这个问题的? 谢谢
