### ISSUE TITLE
读写分离

### ISSUE THREAD

**Issue by dale19900108** [dangdangdotcom/sharding-jdbc#319]
测试读写分离的时候，发现这么两个问题
第一，是select for update 的sql无法走主库，这类的sql，因为走到了从库，导致了记录无法锁定，造成了数据的修改。
第二，带事务的方法，没有一直走主库。举例，在A方法带事物标记，A中调用了BC两个带事务的方法，B中创建了一条记录，因为事务没提交，导致C中的查询是无法查询到这条记录的。公司采用JPA+hibernate，这种问题就出现的比较多。
为什么在设计读写分离的时候，没有把事务方法内的查询也走主库呢？

**Comment by terrymanu** [comment]
第一个问题，可以使用hint强制主库的方式达成。
第二个问题，我不认为读写分离还需要开启事务，这样的性能还不如不做读写分离。

**Comment by moxingwang** [comment]
第二个问题，同样也遇到，建议把hint做出一个注解，方便调用者使用。

**Comment by ypg521** [comment]
@terrymanu   还麻烦有空的时候给个回复
