### ISSUE TITLE
sharding-jdbc-config-common编译问题

### ISSUE THREAD

**Issue by bwzhang2011** [dangdangdotcom/sharding-jdbc#32]
@hanahmily, 编译1.1.0-SNAPSHOT标题组件的时候，*.common.internal 下的ConfigUtil类一直编译不通过。经定位是GROOVY包没有引用正确的缘故，由于indy一直无法正常导入，更新替代成下面则可编译通过
       <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            
            <version>2.4.6</version>
        </dependency>
——注释掉classifiier，将artifactid调整为groovy-all并注明其版本（如2.4.6）
我对groovy不了解，考虑到ALL的包比较大（应该不需要All，但indy方式不清楚无法下载依赖JAR参与编译），可否说明一下（若上述存在问题，也希望能指出）

**Comment by hanahmily** [comment]
首先如果使用maven命令行是可以完成编译和的，这个travis已经证明了这点。那么剩下的原因我猜测你是使用IDE工具无法编译通过。开发人员这边分别使用了IntelliJ IDEA和Eclipse都可以正常使用。indy编译版是针对jdk7以上版本的性能优化版，请保证你的ide可以正确识别classifier节点。
