### ISSUE TITLE
中文文档有错

### ISSUE THREAD

**Issue by xawei** [dangdangdotcom/sharding-jdbc#321]
[中文文档](http://dangdangdotcom.github.io/sharding-jdbc/02-guide/sharding/)的"2. 使用指南-分库分表"部分，“构造ShardingDataSource”一小节的代码有误：
```java
DataSource dataSource = new ShardingDataSourceFactory.createDataSource(shardingRule);
```
调用类ShardingDataSourceFactory的静态方法时，多写了一个new.

英文文档没错。

**Comment by terrymanu** [comment]
fixed at 1.5.1
