### ISSUE TITLE
spring的命名空间，总是找不到xsd地址，报错

### ISSUE THREAD

**Issue by xiaojianyu315** [dangdangdotcom/sharding-jdbc#326]
org.xml.sax.SAXParseException; lineNumber: 14; columnNumber: 164; schema_reference.4: 无法读取方案文档 'http://www.dangdang.com/schema/ddframe/rdb/rdb.xsd', 原因为 1) 无法找到文档; 2) 无法读取文档; 3) 文档的根元素不是 <xsd:schema>。

**Comment by terrymanu** [comment]
请自行阅读faq文档

**Comment by xiaojianyu315** [comment]
非常感谢

**Comment by budingts** [comment]
faq文档在哪里啊

**Comment by WSharkCoder** [comment]
同问faq文档

**Comment by WSharkCoder** [comment]
FAQ文档找到了！[中文FAQ文档](https://shardingsphere.apache.org/document/current/cn/faq/)
