### ISSUE TITLE
生产环境分了200张表，sql日志输出太多，建议默认关闭sql.show

### ISSUE THREAD

**Issue by ChrisAdvance** [dangdangdotcom/sharding-jdbc#327]
### Which version of Sharding-Jdbc do you using?
<sharding-jdbc.version>1.5.0</sharding-jdbc.version>

### Expected behavior
不配置sql.show属性，默认为关闭

### Actual behavior
没有配置sql.show，但是默认为开启
控制台输出日志如下：
[INFO] [2017-08-11 10:54:08,644] [Sharding-JDBC-SQL] [http-nio-8140-exec-7] [] [] [] Actual SQL: singleDB ::: select

### Steps to reproduce the behavior
不配置sql.show, 正常case跑

### Please provide the reproduce example codes (such as github link) if possible.
建议这两个参数都能默认为false
```
        <rdb:props>
            <prop key="metrics.enable">false</prop>
            <prop key="sql.show">false</prop>
        </rdb:props>
```

**Comment by terrymanu** [comment]
fixed at 1.5.1
