### ISSUE TITLE
limit 支持问题

### ISSUE THREAD

**Issue by pingww** [dangdangdotcom/sharding-jdbc#33]
不支持 limit 1 offset 10  
不支持 limit 100 , -1

**Comment by hanahmily** [comment]
对于第一个 limit 1 offset 10 。Sharding-JDBC是支持的，我讲提交新的测试用例去说明这点。

对于第二种 limit 100,-1目前MySQL已经不支持了。
[MySQL 5.5 select 文档](https://dev.mysql.com/doc/refman/5.5/en/select.html)
