### ISSUE TITLE
insert into无法分片路由

### ISSUE THREAD

**Issue by liu1028** [dangdangdotcom/sharding-jdbc#330]
我用的是1.5.0版本，但是执行简单的mybatis插入操作，比如：
`insert into t_order (order_id,user_id) values (#{orderId}, #{userId} )`
上述语句没有根据我table-rule给定的order_id进行分表操作，而是报错:
**no table rule or default database source**
但是select，update，delete却都是可以正确路由的。

文档上说：分片键只是从where语句后提取。那么insert就不能分片了吗？我之后用了
HintManager还是不成功。

折磨一天了，希望帮我看看

**Comment by terrymanu** [comment]
insert同样可以正常使用。example中有正常使用的案例。
