### ISSUE TITLE
insert 分片问题

### ISSUE THREAD

**Issue by liu1028** [dangdangdotcom/sharding-jdbc#333]
我测试了一下insert分片的问题，发现mybatis的不能分片并且报错找不到分片，但是我从
springIOC容器直接取得shardingDatasource进行原生jdbc操作是可以的。

我的xml配置是这样的：
 `<rdb:table-rule logic-table="t_order" database-strategy="userIdDSStrategy" table-strategy="orderIdTblStrategy" actualtables="db0.t_order_${0..1},db1.t_order_${2..3},db2.t_order_${4..5}">
 </rdb:table-rule>`

mapper XML：
 ` <insert id="insertOrder">
         insert into t_order (order_id,  user_id) VALUES (#{orderId},  #{userId})
  </insert>`

测试代码：
  `  @Test
    public void testInsertWithGeneralKey(){
        Order o1=new Order();
        Long id=keyGenerator.generateKey().longValue();
        o1.setOrderId(id);
        o1.setUserId(999);

        orderService.insert(o1);
    }`

报错信息：Cannot find table rule and default data source with logic table: 't_order_0'

希望得到解决

**Comment by terrymanu** [comment]
没有配置分库分表策略导致的。
报错信息已经说明了：Cannot find table rule and default data source with logic table: 't_order_0'
