### ISSUE TITLE
order by  语句解析，如果有函数，会把后面的 asc,desc解析到OrderItem name属性中。

### ISSUE THREAD

**Issue by javaside** [dangdangdotcom/sharding-jdbc#334]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5.1

如图
### Please provide the reproduce example codes (such as github link) if possible.
<img width="898" alt="orderby" src="https://user-images.githubusercontent.com/1187815/29257367-ffa1ee9a-80e3-11e7-9747-970f8a30bb55.png">

**Comment by terrymanu** [comment]
fixed at 1.5.2
