### ISSUE TITLE
不配置data-source-names="db_0" 自动使用default-data-source="db_0" 

### ISSUE THREAD

**Issue by Cyao99** [dangdangdotcom/sharding-jdbc#337]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5.1

### Expected behavior
不配置data-source-names="db_0" 自动使用default-data-source="db_0" 
由于db_1中没有t_user表 t_user表也没有配置分库策略
查询时会查询db_1 肯定找不到表
<rdb:data-source id="shardingDataSource">
		<rdb:sharding-rule data-sources="db_0,db_1"
			default-data-source="db_0">
			<rdb:table-rules>
				<rdb:table-rule logic-table="t_user" actual-tables="t_user_${0..2}"
					data-source-names="db_0" table-strategy="userTableStrategy" />

				<rdb:table-rule logic-table="t_order"
					actual-tables="t_order_${201708..201712},t_order_201801"
					database-strategy="databaseStrategy" table-strategy="orderTableStrategy" />

			</rdb:table-rules>
		</rdb:sharding-rule>
		<rdb:props>
			<prop key="sql.show">true</prop>
		</rdb:props>
	</rdb:data-source>

### Actual behavior
       不配置data-source-names="db_0" 自动使用default-data-source="db_0"

**Comment by terrymanu** [comment]
sharding-jdbc的配置是希望尽量清晰。对于不配置的表，不会进行自动的猜测性质的路由
