### ISSUE TITLE
分库下的join支持？

### ISSUE THREAD

**Issue by Cyao99** [dangdangdotcom/sharding-jdbc#338]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5.1
### Expected behavior
支持分库逻辑表db_0.t_order db_1.t_order 和普通逻辑表db_0.t_user join实现
### Actual behavior
由于配置t_user data-source-names="db_0" 的缘故
只会查询db_0的t_order表

**Comment by terrymanu** [comment]
此功能应该是从1.0.0版本开始就支持的。但是有两个注意事项。
1. db_1.t_order 和 db_0.t_user走的是笛卡尔积，性能较差
2. sharding-jdbc的前提是水平分片，db_0和db_1都必须同时存在t_order和t_user
