### ISSUE TITLE
MySQL limit取特定页数的数据问题

### ISSUE THREAD

**Issue by komawei** [dangdangdotcom/sharding-jdbc#342]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5.0.M2

问题：
订单表使用了sjdbc进行分表，ID是使用snowflake生成的分布式主键，不连续
前台订单管理页面需要用到分页，
例如未分表情况下，我第一页取的数据是limit 0, 10，第五页取的应该是limit 50, 10
由于sjdbc会对limit进行SQL改写，改写后变成了limit 0, 60
这样前台获取到的就会是60条数据而不是10条

请问在这种情况下，我要从第一页直接取第五页的数据，如何取比较合适？
或者以后的版本会更新自动返回所需条数的数据（本例中是10条）？

我看“更好的分页解决方案”中，只阐述了如何取下一页的数据，并没有说明跨页的处理方式。
求解答

**Comment by terrymanu** [comment]
分页对于sql改写是没有错的。可以网上搜索相关资料。
issue我关闭了。

**Comment by komawei** [comment]
=。=
我没说这样改写有错，只是想问一下，如果我取第100000页的时候，SQL会被改写为0, 100010，
这样不会内存溢出吗

**Comment by komawei** [comment]
@terrymanu 求解答， 我现在的问题就是如何能在多分片的情况下定位到比如第10000页的最后一条数据的ID
