### ISSUE TITLE
读写分离1主多从配置的时候，如果其中一台从数据库down掉，会导致整个数据源不可用的问题

### ISSUE THREAD

**Issue by tangmin721** [dangdangdotcom/sharding-jdbc#350]
### Which version of Sharding-Jdbc do you using?
1.5.2
### Expected behavior
   定义读写分离数据源, 读写分离数据源实现了DataSource接口, 可直接当做数据源处理 ，多个从用逗号隔开（如果从数据库其中一台连接不上，不知道为什么会报错）
    <rdb:master-slave-data-source id="ds_0" master-data-source-ref="ds_0_master" slave-data-sources-ref="ds_0_slave_0,ds_0_slave_1" />

**Comment by terrymanu** [comment]
数据库治理方面将会在1.6.0统一做
