### ISSUE TITLE
regexp support 

### ISSUE THREAD

**Issue by denghc0607** [dangdangdotcom/sharding-jdbc#356]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
  1.5.3
### Please provide the reproduce example codes (such as github link) if possible.
my sql as below: 
     select * from resourcetable where TITLE REGEXP 'abc' order by UPDTIME desc limit 0,1
sharding-columns : UPDTIME
the question is that when i use this sql to query resourcetable ,i got two records from two different Physical tables,  so limit 0,1 doesn't work

**Comment by terrymanu** [comment]
fixed at 1.5.4
