### ISSUE TITLE
动态分表在无分库规则的情况下，会去多个库查询

### ISSUE THREAD

**Issue by amikehero** [dangdangdotcom/sharding-jdbc#358]
Please answer these questions before submitting your issue. Thanks!

### Expected behavior

在没有配置分库规则情况下，去默认数据库

### Actual behavior

实际是去sharding-jdbc数据源中配置的多个数据库查询

### Steps to reproduce the behavior

    <rdb:strategy id="tableDynamicShardingStrategy" sharding-columns="order_id"
        algorithm-class="com.dangdang.ddframe.rdb.sharding.example.jdbc.algorithm.SingleKeyDynamicModuloTableShardingAlgorithm" />
	<rdb:data-source id="shardingDataSource">
		<rdb:sharding-rule data-sources="ds_0, 
		ds_1"  default-data-source="ds_1">
			<rdb:table-rules>
				<rdb:table-rule logic-table="t_order_dynamic" dynamic="true"
                    table-strategy="tableDynamicShardingStrategy" />
			</rdb:table-rules>
		</rdb:sharding-rule>
	    <rdb:props>
            <prop key="sql.show">true</prop>
        </rdb:props>
        
	</rdb:data-source>

SQL解析如下：

[INFO ] 2017-09-05 20:05:37,326 --main-- [Sharding-JDBC-SQL] Logic SQL: SELECT
         
        order_id,
        user_id,
        status
     
        FROM `t_order_dynamic` where order_id=2 order by user_id DESC 
[INFO ] 2017-09-05 20:05:37,326 --main-- [Sharding-JDBC-SQL] SQLStatement: SelectStatement(super=AbstractSQLStatement(type=SELECT, tables=Tables(tables=[Table(name=t_order_dynamic, alias=Optional.absent())]), conditions=Conditions(conditions={Column(name=order_id, tableName=t_order_dynamic)=Condition(column=Column(name=order_id, tableName=t_order_dynamic), operator=EQUAL, positionValueMap={0=2}, positionIndexMap={})}), sqlTokens=[TableToken(beginPosition=86, originalLiterals=`t_order_dynamic`)]), distinct=false, containStar=false, selectListLastPosition=81, groupByLastPosition=0, items=[CommonSelectItem(expression=order_id, alias=Optional.absent()), CommonSelectItem(expression=user_id, alias=Optional.absent()), CommonSelectItem(expression=status, alias=Optional.absent())], groupByItems=[], orderByItems=[OrderItem(owner=Optional.absent(), name=Optional.of(user_id), type=DESC, index=-1, alias=Optional.absent())], limit=null) 
[INFO ] 2017-09-05 20:05:37,326 --main-- [Sharding-JDBC-SQL] Actual SQL: ds_0 ::: SELECT
         
        order_id,
        user_id,
        status
     
        FROM t_order_0 where order_id=2 order by user_id DESC 
[INFO ] 2017-09-05 20:05:37,326 --main-- [Sharding-JDBC-SQL] Actual SQL: ds_1 ::: SELECT
         
        order_id,
        user_id,
        status
     
        FROM t_order_0 where order_id=2 order by user_id DESC 
[order_id: 2, user_id: 20, status: UPDATE_1]

**Comment by terrymanu** [comment]
查出来的数据没错吧？

**Comment by amikehero** [comment]
亮哥，测试用的，数据没有错。是去到了两个数据库。
我之前理解是只分表不分库的只会去到默认数据库，现在看来是我理解有误。
