### ISSUE TITLE
1.5.3不能正常使用mysql的自增主键 报错 Generated keys not requested. 

### ISSUE THREAD

**Issue by Yao99** [dangdangdotcom/sharding-jdbc#360]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5.3
### Expected behavior

1.5.2可以正常使用mysql的自增主键

### Actual behavior

Generated keys not requested. You need to specify Statement.RETURN_GENERATED_KEYS to Statement.executeUpdate() or Connection.prepareStatement().

### Steps to reproduce the behavior
CREATE TABLE `sequence` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

public Long getSequence() {
		Sequence sequence = new Sequence();
		testDao.getSequence(sequence);
		return sequence.getId();
}
<insert id="getSequence" parameterType="com.cyao.entity.Sequence" useGeneratedKeys="true" keyProperty="id">
	insert into sequence() values()
</insert>

**Comment by terrymanu** [comment]
信息不足，请提供可供重现的代码。
或者全部的sql.show日志、ShardingRule配置、SQL以及调用SQL的代码片段

**Comment by fugaoyang** [comment]
我同样遇到的是 ：在插入非分片表时，报了这样的错：
Caused by: java.sql.SQLException: Generated keys not requested.
 You need to specify Statement.RETURN_GENERATED_KEYS to Statement.executeUpdate() or Connection.prepareStatement().
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1084)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:973)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:918)
	at com.mysql.jdbc.StatementImpl.getGeneratedKeys(StatementImpl.java:1971)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.getGeneratedKeys(NewProxyPreparedStatement.java:1749)
	at com.dangdang.ddframe.rdb.sharding.jdbc.core.statement.ShardingPreparedStatement.getGeneratedKeys(ShardingPreparedStatement.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

我用的spring mybatis ,插入的mapper.xml配置如下：
<insert id="insert" parameterType="com.xx.model.TradeRequest"
		useGeneratedKeys="true" keyProperty="id">
------
sharding rule配置如下：
<rdb:data-source id="shardingDataSource">
		<rdb:sharding-rule data-sources="dataSource.cts" default-data-source="dataSource.cts"  
		     key-generator-class="com.biz.sharding.IncrementKeyGenerator">
			<rdb:table-rules>
				<rdb:table-rule logic-table="CTS_VACCO_PAYMENT_DETAIL" 
				actual-tables="CTS_VACCO_PAYMENT_DETAIL_0,CTS_VACCO_PAYMENT_DETAIL_1,CTS_VACCO_PAYMENT_DETAIL_2,CTS_VACCO_PAYMENT_DETAIL_3" 
				table-strategy="paymentDetailTableStrategy" >
				  <rdb:generate-key-column column-name="id"/>
				</rdb:table-rule>
			</rdb:table-rules>
		   <rdb:binding-table-rules>
                <rdb:binding-table-rule logic-tables="CTS_VACCO_PAYMENT_DETAIL"/>
            </rdb:binding-table-rules> 
            <rdb:default-table-strategy sharding-columns="none"
             algorithm-class="com.dangdang.ddframe.rdb.sharding.api.strategy.table.NoneTableShardingAlgorithm"/>
		</rdb:sharding-rule>
		 <rdb:props>
            <prop key="metrics.enable">true</prop>
            <prop key="sql.show">true</prop>
        </rdb:props>
    </rdb:data-source>

**Comment by terrymanu** [comment]
请一次性将所需信息提供完善吧。这样沟通成本太高，一天就这么过去了。

**Comment by fugaoyang** [comment]
我用的spring mybatis ,插入的mapper.xml配置如下：
<insert id="insert" parameterType="com.xx.model.TradeRequest"
		useGeneratedKeys="true" keyProperty="id">
sharding rule配置如下：
<rdb:data-source id="shardingDataSource">
		<rdb:sharding-rule data-sources="dataSource.cts" default-data-source="dataSource.cts"  
		     key-generator-class="com.biz.sharding.IncrementKeyGenerator">
			<rdb:table-rules>
				<rdb:table-rule logic-table="CTS_VACCO_PAYMENT_DETAIL" 
				actual-tables="CTS_VACCO_PAYMENT_DETAIL_0,CTS_VACCO_PAYMENT_DETAIL_1,CTS_VACCO_PAYMENT_DETAIL_2,CTS_VACCO_PAYMENT_DETAIL_3" 
				table-strategy="paymentDetailTableStrategy" >
				  <rdb:generate-key-column column-name="id"/>
				</rdb:table-rule>
			</rdb:table-rules>
		   <rdb:binding-table-rules>
                <rdb:binding-table-rule logic-tables="CTS_VACCO_PAYMENT_DETAIL"/>
            </rdb:binding-table-rules> 
            <rdb:default-table-strategy sharding-columns="none"
             algorithm-class="com.dangdang.ddframe.rdb.sharding.api.strategy.table.NoneTableShardingAlgorithm"/>
		</rdb:sharding-rule>
		 <rdb:props>
            <prop key="metrics.enable">true</prop>
            <prop key="sql.show">true</prop>
        </rdb:props>
    </rdb:data-source>

**Comment by terrymanu** [comment]
请参见之前的信息：
信息不足，请提供可供重现的代码。
或者提供全部的sql.show日志、ShardingRule配置、SQL以及调用SQL的代码片段

请一次性提供所需信息，不然是在不易定位

**Comment by Cyao99** [comment]
![1](https://user-images.githubusercontent.com/10820724/30194797-f6cec326-9487-11e7-96f8-d834d1756144.png)
![2](https://user-images.githubusercontent.com/10820724/30194798-f6fd1866-9487-11e7-8f04-8e078edd52b3.png)
![3](https://user-images.githubusercontent.com/10820724/30194799-f712cf12-9487-11e7-9a70-aabbcb75d743.png)
![4](https://user-images.githubusercontent.com/10820724/30194800-f727eb5e-9487-11e7-941e-b48f0771c05b.png)
![5](https://user-images.githubusercontent.com/10820724/30194801-f72d7f42-9487-11e7-84d9-d85640bd7e2a.png)
![6](https://user-images.githubusercontent.com/10820724/30194803-f72ea69c-9487-11e7-94ca-8d26a5dce79b.png)
![7](https://user-images.githubusercontent.com/10820724/30194802-f72ed2de-9487-11e7-93e2-bce796682ed7.png)
![8](https://user-images.githubusercontent.com/10820724/30194804-f732f3e6-9487-11e7-8842-80fab4e544ac.png)

**Comment by terrymanu** [comment]
您这样的代码片段对于我们定位bug并无实质用途。请按照之前交流所写。提供我们需要的信息。
最好提供一个可供重现的demo，并将代码放在guthub上，将连接交给我们。
时间精力有限，请大家各司其职。
我们负责修改bug，请您负责将bug以最低的理解成本重现在我们面前，谢谢合作。

**Comment by terrymanu** [comment]
由于您没提供可重现的代码，并自行关闭了issue。
因此这个issue我算为invalid了

**Comment by terrymanu** [comment]
dup #370
