### ISSUE TITLE
1.5.2非分片表查询报错

### ISSUE THREAD

**Issue by Yao99** [dangdangdotcom/sharding-jdbc#361]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5.2
### Expected behavior

1.5.1版本正常 1.5.3版本也解决了 可是 1.5.3 不支持原生
自增主键 #360 
怎么感觉更新的时候 会把原来的bug重新更新出来  1.5.0不支持原生自增主键 1.5.1更新了 

后面的 1.5.2 更新不能查询非分片表  1.5.3 更新的不能使用自增主键

**Comment by terrymanu** [comment]
信息不足，请提供可供重现的代码。
或者提供全部的sql.show日志、ShardingRule配置、SQL以及调用SQL的代码片段

如果只看字面上的意思，1.5.3是支持非分片并配置default-data-source查询的，因此目前的描述不足以断定issue的充要条件。

**Comment by Cyao99** [comment]
![1](https://user-images.githubusercontent.com/10820724/30194884-7d20f8e0-9488-11e7-965e-0412b9bdaa0c.png)
![2](https://user-images.githubusercontent.com/10820724/30194885-7d23df74-9488-11e7-87cb-be481934e60b.png)
![3](https://user-images.githubusercontent.com/10820724/30194886-7d4022ce-9488-11e7-8b83-33b0ea64c352.png)
![4](https://user-images.githubusercontent.com/10820724/30194888-7d6b7384-9488-11e7-8343-bdaff47562d0.png)
![5](https://user-images.githubusercontent.com/10820724/30194889-7d6be7c4-9488-11e7-9b0e-aacdf83bd8e6.png)
![6](https://user-images.githubusercontent.com/10820724/30194887-7d6ad8ca-9488-11e7-8fd4-50b2d02ccb0f.png)
![7](https://user-images.githubusercontent.com/10820724/30194890-7d83059e-9488-11e7-8d30-7dcb9844711d.png)

**Comment by terrymanu** [comment]
既然这个问题已经在1.5.3解决了，我就关闭了。
dup with ISSUE #351
