### ISSUE TITLE
sharding1.53多数据源不分片表与分片表关联查询出错

### ISSUE THREAD

**Issue by xuecf8679** [dangdangdotcom/sharding-jdbc#364]
我用的是1.53版本，做分库但是不分表，连接的是sqlserver2008数据库，配置了2个数据源，第一个数据源里有2个表，分别是carPosition_1和carInfo，第二个数据源里只有carPosition_1，因为我的carPosition_1要按照车牌号来分库，但是carInfo不分库。现在我在程序里对carPosition_1和carInfo做关联查询，查询的语句为：select b.company as company1 from carPosition_1 a left outer join carInfo b on a.carNo=b.carNo，但是执行时报错，提示对象名 'carInfo' 无效。我把整个项目打包上传上来，是个普通的web项目，非maven项目，请看一下是什么原因

**Comment by xuecf8679** [comment]
我的项目传不上来啊，不知道为什么

**Comment by xuecf8679** [comment]
只能贴代码了：
<bean id="dataSource_lu" class="org.apache.commons.dbcp.BasicDataSource"
		destroy-method="close">
		<property name="driverClassName" value="${dataSource_lu.driverClassName}" />
		<property name="url" value="${dataSource_lu.url}" />
		<property name="username" value="${dataSource_lu.username}" />
		<property name="password" value="${dataSource_lu.password}" />
		<property name="maxActive" value="${dataSource_lu.maxActive}" />
		<property name="maxIdle" value="${dataSource_lu.maxIdle}" />
		<property name="minIdle" value="${dataSource_lu.minIdle}" />
		<property name="maxWait" value="${dataSource_lu.maxWait}" />
		<property name="removeAbandoned" value="${dataSource_lu.removeAbandoned}" />
		<property name="removeAbandonedTimeout" value="${dataSource_lu.removeAbandonedTimeout}" />
		<property name="logAbandoned" value="${dataSource_lu.logAbandoned}" />
		<property name="testWhileIdle" value="${dataSource_lu.testWhileIdle} " />
		<property name="validationQuery" value="${dataSource_lu.validationQuery}" />
		<property name="timeBetweenEvictionRunsMillis" value="${dataSource_lu.timeBetweenEvictionRunsMillis}" />
		<property name="numTestsPerEvictionRun" value="${dataSource_lu.maxActive}" />
		<property name="minEvictableIdleTimeMillis" value="${dataSource_lu.minEvictableIdleTimeMillis}" />
	</bean>
	<bean id="dataSource_ji" class="org.apache.commons.dbcp.BasicDataSource"
		destroy-method="close">
		<property name="driverClassName" value="${dataSource_ji.driverClassName}" />
		<property name="url" value="${dataSource_ji.url}" />
		<property name="username" value="${dataSource_ji.username}" />
		<property name="password" value="${dataSource_ji.password}" />
		<property name="maxActive" value="${dataSource_ji.maxActive}" />
		<property name="maxIdle" value="${dataSource_ji.maxIdle}" />
		<property name="minIdle" value="${dataSource_ji.minIdle}" />
		<property name="maxWait" value="${dataSource_ji.maxWait}" />
		<property name="removeAbandoned" value="${dataSource_ji.removeAbandoned}" />
		<property name="removeAbandonedTimeout" value="${dataSource_ji.removeAbandonedTimeout}" />
		<property name="logAbandoned" value="${dataSource_ji.logAbandoned}" />
		<property name="testWhileIdle" value="${dataSource_ji.testWhileIdle} " />
		<property name="validationQuery" value="${dataSource_ji.validationQuery}" />
		<property name="timeBetweenEvictionRunsMillis" value="${dataSource_ji.timeBetweenEvictionRunsMillis}" />
		<property name="numTestsPerEvictionRun" value="${dataSource_ji.maxActive}" />
		<property name="minEvictableIdleTimeMillis" value="${dataSource_ji.minEvictableIdleTimeMillis}" />
	</bean>
	<rdb:strategy id="databaseStrategy_carPosition" sharding-columns="carNo" algorithm-class="sharding.DatabaseShardingAlgorithm_carPosition"/>
	<rdb:data-source id="dataSource_sharding">
        <rdb:sharding-rule data-sources="dataSource_lu,dataSource_ji" default-data-source="dataSource_lu">
            <rdb:table-rules>
                <rdb:table-rule logic-table="carPosition_1" actual-tables="carPosition_1" database-strategy="databaseStrategy_carPosition"/>
                <rdb:table-rule logic-table="carInfo" actual-tables="carInfo"/>
            </rdb:table-rules>
            
        	<rdb:default-database-strategy sharding-columns="none" algorithm-class="com.dangdang.ddframe.rdb.sharding.api.strategy.database.NoneDatabaseShardingAlgorithm"/>
        	<rdb:default-table-strategy sharding-columns="none" algorithm-class="com.dangdang.ddframe.rdb.sharding.api.strategy.table.NoneTableShardingAlgorithm"/>
        </rdb:sharding-rule>
        <rdb:props>
            <prop key="metrics.enable">false</prop>
        </rdb:props>
    </rdb:data-source>

	
	<bean id="jdbcDao_lu" parent="dorado.jdbcDaoTemplate">
		<property name="dataSource" ref="dataSource_lu"/>
	</bean>
	
	<bean id="jdbcDao_ji" parent="dorado.jdbcDaoTemplate">
		<property name="dataSource" ref="dataSource_ji"/>
	</bean>
	
	<bean id="jdbcDao_sharding" parent="dorado.jdbcDaoTemplate">
		<property name="dataSource" ref="dataSource_sharding"/>
	</bean>

测试类：
public class TestEngineStartup extends EngineStartupListener{
	public void onStartup(){
		MyJdbcDao mjd=MyJdbcDao.getInstance("jdbcDao_sharding");
		//String sql="insert into carPosition_1(carNo,gpsTime,speed,lon,lat,address) values(?,?,?,?,?,?)";
		//mjd.executeIUD(sql,"鲁AXC949",new Date(),68,129.345678,34.876543,"胶州湾高速");
		//System.out.println("##########insert语句执行完毕!");
		String qsql="select b.company as company1 from carPosition_1 a left outer join carInfo b on a.carNo=b.carNo where a.carNo=?";
		List<Record> list=mjd.queryForMyRecordList(qsql,"吉AXC949");
		for(int i=0;i<list.size();i++){
			Record r=list.get(i);
			String company=r.getString("company1");
			System.out.println("##########company="+company);
		}
	}
}

**Comment by xuecf8679** [comment]
我的项目是个普通的web项目，直接放到tomcat下启动，会自动运行测试类TestEngineStartup，只不过测试类会报错，会报对象名 'carInfo' 无效，但是项目可以启动的起来，其中项目会直接连接我们的测试数据库，项目git地址为：https://github.com/xuecf8679/demo.git

**Comment by terrymanu** [comment]
请提供可使用maven打包，并直接用main方法运行的可重现demo

**Comment by haocao** [comment]
第二个数据源里只有carPosition_1，没有carInfo。因此如果当路由到第二个数据源时，select b.company as company1 from carPosition_1 a left outer join carInfo b on a.carNo=b.carNo报错是正常的。如果carInfo属于公共库的表，请参考example中相关配置。

**Comment by xuecf8679** [comment]
您好，上面说是请参考example中的相关配置，这个example在哪呢？我看了好多例子了，但是并没有您说的这种配置例子啊，包括官方教程上的配置也没有这种例子啊，能给出下载地址吗？
