### ISSUE TITLE
使用sharding-jdbc执行insert into table(userid) values (123) 的时候，我指定了一个泛型为Long的 SingleKeyTableShardingAlgorithm，然后我遇到了ClassCastException: Integer can not cast to Long

### ISSUE THREAD

**Issue by jurimengs** [dangdangdotcom/sharding-jdbc#367]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5.2
### Expected behavior
数据库能向user表插入 int(11) 类型的值
### Actual behavior
不能插入，报 java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
### Steps to reproduce the behavior
sql:
String sql  = "insert into table (userId) values (11)";
分片算法类：

public classTableShardingByLong implements SingleKeyTableShardingAlgorithm<Long> {
    	/**
	 * 查询条件是=的时候
	 */
	public String doEqualSharding(Collection<String> tableNames,
			ShardingValue<Long> shardingValue) {
                // 
		System.out.println(shardingValue.getValue()); // 这一行会正常log出来
		System.out.println(shardingValue.getValue().longValue()); // 这一行就会报异常,
                // java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
		// ...
                return null;
	}
}
通过调试，我发现TableShardingByLong 类的泛型在编译期，并没有将其类型转嫁给 ShardingValue的泛型， ShardingValue里面get出来的值，虽然引用是Long型，但是它的实例却仍然是 Integer类型的，因此报ClassCastException
![default](https://user-images.githubusercontent.com/10648133/30208674-264d7c98-94c7-11e7-8cb7-947d74132a30.png)

**Comment by haocao** [comment]
由于数据库user表中该字段为int(11) 类型，因此泛型所对应的分片类型应为Integer，如果需要配置为Long类型，请保证数据库该字段类型为bigint。

**Comment by terrymanu** [comment]
请参见：http://shardingjdbc.io/docs/01-start/faq/ 第12个问题
