### ISSUE TITLE
无法返回MySQL自增的order_id

### ISSUE THREAD

**Issue by wjwei** [dangdangdotcom/sharding-jdbc#369]
使用官方的sharding-jdbc-example-mybatis工程无法返回MySQL自增的order_id字段，snowflake算法的order_id是可以成功返回的，只是修改了sharding-jdbc-example-mybatis的数据源，注释掉Main.java里面的其他方法，只留fooService()方法的调用，如图：
![image](https://user-images.githubusercontent.com/4329696/30261321-a454ac9a-96fe-11e7-8a2d-011de7116b77.png)
其他没做任何的配置修改。

**Comment by terrymanu** [comment]
Sharding-JDBC可以支持返回原生的自增主键。但原生自增主键有使用限制，即不能将原生自增主键同时作为分片键使用。

由于Sharding-JDBC并不知晓数据库的表结构，而原生自增主键是不包含在原始SQL中内的，因此Sharding-JDBC无法将该字段解析为分片字段。如自增主键非分片键，则无需关注，可正常返回；若自增主键同时作为分片键使用，Sharding-JDBC无法解析其分片值，导致SQL路由至多张表，从而影响应用的正确性。

而原生自增主键返回的前提条件是INSERT SQL必须最终路由至一张表，因此，面对返回多表的INSERT SQL，自增主键则会返回零。

示例中，正是由于分片键同时为自增主键导致，请知晓。
