### ISSUE TITLE
issue364的解答未明白

### ISSUE THREAD

**Issue by xuecf8679** [dangdangdotcom/sharding-jdbc#371]
https://github.com/dangdangdotcom/sharding-jdbc/issues/364
在上面地址中我问了一个问题，下方给出了一个解答，但是我还没搞清楚，能否说的再详细一点，解答中提到：“如果carInfo属于公共库的表，请参考example中相关配置。”，请问在spring配置文件中如何来配置公共库的表？让我参考的example在哪？我因为我发现配置了default-data-source并没有起作用啊，所以才找不到路由，还请详细解答一下

**Comment by terrymanu** [comment]
sharding-jdbc是需要水平扩展的。db1里有carInfo，db2里没有carInfo，写一条sql查询db1和db2，这种场景sjdbc不支持。
