### ISSUE TITLE
从1.4.2升级到1.5.3后，Group by 后没有数据

### ISSUE THREAD

**Issue by jianchuliu** [dangdangdotcom/sharding-jdbc#376]
问题：从版本1.4.2升级到1.5.3后，原来正常的语句查询不出结果了，几张分库分表规则一致的表
           acp_deduct_batch_merge_details ，acp_agreement ，acp_agreement_account
           根据输入的参数都会定义到其后缀为07的物理表，
           根据实际的物理标join查询出的结果为2条，使用sj后，返回0条
SQL  : select account.bank_id,account.account_type,count(*) as bank_size from acp_deduct_batch_merge_details details 
inner join acp_agreement agreement on details.agreement_id = agreement.agreement_id 
inner join acp_agreement_account account on account.agreement_id = agreement.agreement_id 
where details.deduct_batch_id = ? and details.deduct_contract_month = ? 
and agreement.contract_date between ? and ? and details.deduct_result = 'Merged' 
and account.deduct_default_flag = 'Y' group by account.bank_id,account.account_type

入参：
        17091305920849081012224(String), 201707(Integer), 20170701(Integer), 20170731(Integer)

分片的日志来看
        传入参数后，定位到物理表  acp_agreement_07

**Comment by terrymanu** [comment]
请提供一下两个条件中的任意一个
1. 可重现的能直接运行的代码
2. sql.show日志、分片规则配置、sql语句执行代码片段

**Comment by terrymanu** [comment]
如果仍旧无法重现，此issue将在下周关闭

**Comment by terrymanu** [comment]
已经在qq群中沟通过，确认无法重现
