### ISSUE TITLE
链接获取后不会自动释放链接，然后报错连接池没有空闲链接，程序卡死

### ISSUE THREAD

**Issue by vsalw** [dangdangdotcom/sharding-jdbc#379]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5.3和1.5.4快照版

### Expected behavior
正常应该会自动获取链接，释放链接，但是实际没有，链接全部是busy....
### Actual behavior
不会释放链接，程序卡死
### Steps to reproduce the behavior
项目启动后随便查询数据库，大概到获取到第100个就获取不到了，一共是一百个链接，下一个查询就会卡死，程序报错没有空闲链接
### Please provide the reproduce example codes (such as github link) if possible.
我是使用这个demo发现还是存在这个问题的，你可以试试
https://github.com/Max010230/ShardingTest

**Comment by terrymanu** [comment]
原因是：使用Mybatis时框架调用Connection.getMetaData()时释放连接不正确导致的问题

**Comment by terrymanu** [comment]
fixed at 1.5.4
