### ISSUE TITLE
<prop key="show.sql">true</prop>并没有打印出任何日志

### ISSUE THREAD

**Issue by bing0101** [dangdangdotcom/sharding-jdbc#380]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5.3
### Expected behavior
show sql
### Actual behavior
配置了show.sql 日志什么也没有打印出来
### Steps to reproduce the behavior
增加<prop key="show.sql">true</prop>，发现并没有打印出任何日志
日志配置：log4j2 + slf4j，级别debug，spring的日志可以正常打印，但是sharding-jdbc没有任何日志打印
### Please provide the reproduce example codes (such as github link) if possible.
```xml
    <rdb:data-source id="shardingDataSource">
        <rdb:sharding-rule data-sources="db0,db1">
            <rdb:table-rules>
                <rdb:table-rule logic-table="order" actual-tables="t_order_${0..1}" database-strategy="databaseStrategy" table-strategy="orderTableStrategy" />
                <rdb:table-rule logic-table="order_item" actual-tables="t_order_item_0, t_order_item_1" database-strategy="databaseStrategy" table-strategy="orderItemTableStrategy" />
            </rdb:table-rules>
        </rdb:sharding-rule>
        <rdb:props>
            <prop key="metrics.enable">true</prop>
            <prop key="show.sql">true</prop>
        </rdb:props>
    </rdb:data-source>

**Comment by terrymanu** [comment]
请认真阅读文档。该配置为为sql.show

**Comment by bing0101** [comment]
非常抱歉

**Comment by pengboyin** [comment]
> 非常抱歉
`<sharding:data-source id="shardingDataSourceSkyWrite">
		<sharding:sharding-rule data-source-names="ds_skyUser_read">
			<sharding:table-rules>
				<sharding:table-rule logic-table="accounts_openaccount"
					actual-data-nodes="ds_skyUser_read.accounts_openaccount$->{0..3}"
					database-strategy-ref="databaseStrategy" table-strategy-ref="accountTableTableStrategy"
					key-generator-ref="accountKeyGenerator" />
			</sharding:table-rules>
		</sharding:sharding-rule>
		<sharding:props>
			<prop key="sql.show">true</prop>
			<prop key="metrics.enable">true</prop>
		</sharding:props>
	</sharding:data-source>`

这样配置之后还是无法打印
