### ISSUE TITLE
查询未分表的表失败

### ISSUE THREAD

**Issue by Alanlxh** [dangdangdotcom/sharding-jdbc#382]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5.3
### Expected behavior
使用mybaits作为orm框架
单个数据源包含分表和没有分表的表
查询没有分表的表正常
### Actual behavior
单个数据源查询未分表的表失败 
### Steps to reproduce the behavior
1.启动项目
2Controller包下的的mapping
3点击控制台的输出 http://localhost:8081/nosdSelect
### Please provide the reproduce example codes (such as github link) if possible.
https://git.oschina.net/lxhs/com.study.demo.git

**Comment by haocao** [comment]
示例代码中
``` java
dataSourceMap.put("messagerobot", createDataSource());
dataSourceMap.put("default", createDataSource());
```
两个数据源是重复的，经验证去掉一个重复数据源就可以查询。

**Comment by Alanlxh** [comment]
dataSourceMap.put("messagerobot", createDataSource());
DataSourceRule dataSourceRule = new DataSourceRule(dataSourceMap,"messagerobot");
最初就是这样的，按照提示修改依然不行。

**Comment by terrymanu** [comment]
fixed at 1.5.4

**Comment by shengyue-z** [comment]
此问题 在关联查询时 容易凸显

**Comment by imadcn** [comment]
是的，关联查询的时候会有这个BUG，单表查询的时候没问题
目前用的1.5.1版本，将所有关联查询的表配置了不分片算法后才可以用
