### ISSUE TITLE
jar包没有上传到maven中心库？

### ISSUE THREAD

**Issue by unaszq** [dangdangdotcom/sharding-jdbc#44]
1.1.0版本的jar包没有上传到maven中心库吗？

**Comment by haocao** [comment]
已经上传过了
http://www.mvnrepository.com/artifact/com.dangdang/sharding-jdbc/1.1.0
http://www.mvnrepository.com/artifact/com.dangdang/sharding-jdbc-core/1.1.0
http://www.mvnrepository.com/artifact/com.dangdang/sharding-jdbc-config-yaml/1.1.0
http://www.mvnrepository.com/artifact/com.dangdang/sharding-jdbc-config-spring/1.1.0

**Comment by terrymanu** [comment]
如有问题请在qq群提问，issue主要用于提bug或功能提升。谢谢

**Comment by TracyBin** [comment]
@terrymanu  你好，我们现在准备在生产使用sharding-jdbc，计划使用最新版本，但发现4.x版本的jar包没有更新到maven仓库，需要等到4.x正式版本发布后才会更新到maven仓库吗？
