### ISSUE TITLE
最近在看源码，求助点问题

### ISSUE THREAD

**Issue by wenweihu86** [dangdangdotcom/sharding-jdbc#52]
1、代码大量使用Lombok，导致eclipse找不到对应方法
2、好多长语句
这两点导致代码看着有点累。。
不过还得硬着头皮看下去

**Comment by jiang2015** [comment]
建议代码格式化，这样看起来不是太累。

**Comment by jiang2015** [comment]
@terrymanu

**Comment by terrymanu** [comment]
讨论问题请使用qq群或wiki，请尽量保持issue有实际意义，尽量可以通过issue展现项目发展的进度历程。
