### ISSUE TITLE
关于：actual-tables="t_order_1,t_order_2,t_order_3"配置， 能否开放一个接口由使用者提供这个配置项内容？

### ISSUE THREAD

**Issue by dzxiang** [dangdangdotcom/sharding-jdbc#62]
现在每次增加新的分表都要修改配置文件并重启服务，不太方便。
通常分表的规则以及分表的实际表名使用方是比较清楚的，通过接口实现的方法返回给SJ，可以实现真正的动态配置，还可以兼顾全路由。

**Comment by terrymanu** [comment]
以后会有元数据管理系统，这些信息会放入注册中心。
使用接口的方式也不一定非常好用。
可以多讨论下

**Comment by terrymanu** [comment]
目前已有inline表达式可以简化配置。只是字符串配置再开放自定义接口难免过于繁琐。目前先不考虑。
