### ISSUE TITLE
spring的rdb命名空间无法解析到。

### ISSUE THREAD

**Issue by nangzi** [dangdangdotcom/sharding-jdbc#86]
```
xmlns:rdb="http://www.dangdang.com/schema/ddframe/rdb"
```
```
http://www.dangdang.com/schema/ddframe/rdb 
http://www.dangdang.com/schema/ddframe/rdb/rdb.xsd
```

**Comment by terrymanu** [comment]
这个经过我们测试是没有问题的，而且已经发布很久了，请看一下自己的namespace配置。谢谢

**Comment by coderew** [comment]
我也遇到了相同的错误，请问如何解决

**Comment by coderew** [comment]
引入以下包可以解决：
<dependency>
      <groupId>com.dangdang</groupId>
      <artifactId>sharding-jdbc-config-spring</artifactId>
       <version>1.4.0</version>
</dependency>

**Comment by duomu** [comment]
我也遇到同样的问题了，求问怎么解决？
直接浏览器访问http://www.dangdang.com/schema/ddframe/rdb/rdb.xsd，跳到当当网去了，根本没有xsd文件
