### ISSUE TITLE
运行实例报错

### ISSUE THREAD

**Issue by empireghost** [dangdangdotcom/sharding-jdbc#94]
org.xml.sax.SAXParseException; lineNumber: 31; columnNumber: 193; schema_reference.4: 无法读取方案文档 'http://www.dangdang.com/schema/ddframe/rdb/rdb.xsd', 原因为 1) 无法找到文档; 2) 无法读取文档; 3) 文档的根元素不是 <xsd:schema>。

http://www.dangdang.com/schema/ddframe/rdb/rdb.xsd  直接访问404

**Comment by terrymanu** [comment]
duplicated with #86。
xsd都在jar包中，并无发布至网上，自行配置命名空间即可

**Comment by duomu** [comment]
求问怎么自己配置命名空间？难道是自己把xsd发布到网上，然后再配成新的地址？
