### ISSUE TITLE
读写分离负载均衡策略支持配置

### ISSUE THREAD

**Issue by wudongpo** [dangdangdotcom/sharding-jdbc#98]
支持读写分离负载均衡策略的策略复写。

**建议的新功能行为**

可以自定以负载均衡算法。并提供技工简单的权重分配算法。
由于部分用户反映其主库的性能会明显高于从库，故该算法可以在主库和从库之间做全局负载策略。而不仅仅是在从库之间

**为什么这个新功能是对大多数用户有用的**

很多用户的服务器性能不同，需要该策略来优化性能

**Comment by hanahmily** [comment]
这个建议不错 可以开放给用户负载均衡算法

**Comment by terrymanu** [comment]
fixed at 1.5.3
